# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\file_pros.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 580)
        MainWindow.setMinimumSize(QtCore.QSize(720, 580))
        MainWindow.setMaximumSize(QtCore.QSize(720, 580))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(4, 0, 4, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.internal_properties_wid = QtWidgets.QWidget()
        self.internal_properties_wid.setObjectName("internal_properties_wid")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.internal_properties_wid)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.internal_properties_wid)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1412, 469))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_2.setMinimumSize(QtCore.QSize(1400, 0))
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.IP_edit_2 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_2.setObjectName("IP_edit_2")
        self.gridLayout_3.addWidget(self.IP_edit_2, 1, 1, 1, 1)
        self.IP_label_3 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_3.setText("")
        self.IP_label_3.setScaledContents(True)
        self.IP_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_3.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_3.setObjectName("IP_label_3")
        self.gridLayout_3.addWidget(self.IP_label_3, 2, 0, 1, 1)
        self.IP_label_2 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_2.setText("")
        self.IP_label_2.setScaledContents(True)
        self.IP_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_2.setObjectName("IP_label_2")
        self.gridLayout_3.addWidget(self.IP_label_2, 1, 0, 1, 1)
        self.IP_label_4 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_4.setText("")
        self.IP_label_4.setScaledContents(True)
        self.IP_label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_4.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_4.setObjectName("IP_label_4")
        self.gridLayout_3.addWidget(self.IP_label_4, 3, 0, 2, 1)
        self.IP_label_5 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_5.setText("")
        self.IP_label_5.setScaledContents(True)
        self.IP_label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_5.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_5.setObjectName("IP_label_5")
        self.gridLayout_3.addWidget(self.IP_label_5, 5, 0, 2, 1)
        self.IP_label_6 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_6.setText("")
        self.IP_label_6.setScaledContents(True)
        self.IP_label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_6.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_6.setObjectName("IP_label_6")
        self.gridLayout_3.addWidget(self.IP_label_6, 7, 0, 1, 1)
        self.IP_label_8 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_8.setText("")
        self.IP_label_8.setScaledContents(True)
        self.IP_label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_8.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_8.setObjectName("IP_label_8")
        self.gridLayout_3.addWidget(self.IP_label_8, 9, 0, 2, 1)
        self.IP_label_7 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_7.setText("")
        self.IP_label_7.setScaledContents(True)
        self.IP_label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_7.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_7.setObjectName("IP_label_7")
        self.gridLayout_3.addWidget(self.IP_label_7, 8, 0, 1, 1)
        self.IP_label_9 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_9.setText("")
        self.IP_label_9.setScaledContents(True)
        self.IP_label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_9.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_9.setObjectName("IP_label_9")
        self.gridLayout_3.addWidget(self.IP_label_9, 11, 0, 1, 1)
        self.IP_edit_7 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_7.setObjectName("IP_edit_7")
        self.gridLayout_3.addWidget(self.IP_edit_7, 8, 1, 1, 1)
        self.IP_edit_8 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_8.setObjectName("IP_edit_8")
        self.gridLayout_3.addWidget(self.IP_edit_8, 9, 1, 1, 1)
        self.IP_edit_5 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_5.setObjectName("IP_edit_5")
        self.gridLayout_3.addWidget(self.IP_edit_5, 5, 1, 2, 1)
        self.IP_edit_4 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_4.setObjectName("IP_edit_4")
        self.gridLayout_3.addWidget(self.IP_edit_4, 3, 1, 2, 1)
        self.IP_label = QtWidgets.QLabel(self.frame_2)
        self.IP_label.setText("")
        self.IP_label.setScaledContents(True)
        self.IP_label.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label.setObjectName("IP_label")
        self.gridLayout_3.addWidget(self.IP_label, 0, 0, 1, 1)
        self.IP_edit_3 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_3.setObjectName("IP_edit_3")
        self.gridLayout_3.addWidget(self.IP_edit_3, 2, 1, 1, 1)
        self.IP_edit_6 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_6.setObjectName("IP_edit_6")
        self.gridLayout_3.addWidget(self.IP_edit_6, 7, 1, 1, 1)
        self.IP_edit = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit.setObjectName("IP_edit")
        self.gridLayout_3.addWidget(self.IP_edit, 0, 1, 1, 1)
        self.IP_edit_9 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_9.setObjectName("IP_edit_9")
        self.gridLayout_3.addWidget(self.IP_edit_9, 11, 1, 1, 1)
        self.IP_edit_10 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_10.setObjectName("IP_edit_10")
        self.gridLayout_3.addWidget(self.IP_edit_10, 12, 1, 2, 1)
        self.IP_label_10 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_10.setText("")
        self.IP_label_10.setScaledContents(True)
        self.IP_label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_10.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_10.setObjectName("IP_label_10")
        self.gridLayout_3.addWidget(self.IP_label_10, 12, 0, 2, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_3)
        self.line = QtWidgets.QFrame(self.frame_2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.IP_label_11 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_11.setText("")
        self.IP_label_11.setScaledContents(True)
        self.IP_label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_11.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_11.setObjectName("IP_label_11")
        self.gridLayout_5.addWidget(self.IP_label_11, 0, 0, 1, 1)
        self.IP_edit_11 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_11.setObjectName("IP_edit_11")
        self.gridLayout_5.addWidget(self.IP_edit_11, 0, 1, 1, 1)
        self.IP_label_12 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_12.setText("")
        self.IP_label_12.setScaledContents(True)
        self.IP_label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_12.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_12.setObjectName("IP_label_12")
        self.gridLayout_5.addWidget(self.IP_label_12, 1, 0, 1, 1)
        self.IP_edit_12 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_12.setObjectName("IP_edit_12")
        self.gridLayout_5.addWidget(self.IP_edit_12, 1, 1, 1, 1)
        self.IP_label_13 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_13.setText("")
        self.IP_label_13.setScaledContents(True)
        self.IP_label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_13.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_13.setObjectName("IP_label_13")
        self.gridLayout_5.addWidget(self.IP_label_13, 2, 0, 1, 1)
        self.IP_edit_13 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_13.setObjectName("IP_edit_13")
        self.gridLayout_5.addWidget(self.IP_edit_13, 2, 1, 1, 1)
        self.IP_label_14 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_14.setText("")
        self.IP_label_14.setScaledContents(True)
        self.IP_label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_14.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_14.setObjectName("IP_label_14")
        self.gridLayout_5.addWidget(self.IP_label_14, 3, 0, 1, 1)
        self.IP_edit_14 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_14.setObjectName("IP_edit_14")
        self.gridLayout_5.addWidget(self.IP_edit_14, 3, 1, 1, 1)
        self.IP_label_15 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_15.setText("")
        self.IP_label_15.setScaledContents(True)
        self.IP_label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_15.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_15.setObjectName("IP_label_15")
        self.gridLayout_5.addWidget(self.IP_label_15, 4, 0, 1, 1)
        self.IP_edit_15 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_15.setObjectName("IP_edit_15")
        self.gridLayout_5.addWidget(self.IP_edit_15, 4, 1, 1, 1)
        self.IP_label_16 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_16.setText("")
        self.IP_label_16.setScaledContents(True)
        self.IP_label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_16.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_16.setObjectName("IP_label_16")
        self.gridLayout_5.addWidget(self.IP_label_16, 5, 0, 1, 1)
        self.IP_edit_16 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_16.setObjectName("IP_edit_16")
        self.gridLayout_5.addWidget(self.IP_edit_16, 5, 1, 1, 1)
        self.IP_label_17 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_17.setText("")
        self.IP_label_17.setScaledContents(True)
        self.IP_label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_17.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_17.setObjectName("IP_label_17")
        self.gridLayout_5.addWidget(self.IP_label_17, 6, 0, 1, 1)
        self.IP_edit_17 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_17.setObjectName("IP_edit_17")
        self.gridLayout_5.addWidget(self.IP_edit_17, 6, 1, 1, 1)
        self.IP_label_18 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_18.setText("")
        self.IP_label_18.setScaledContents(True)
        self.IP_label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_18.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_18.setObjectName("IP_label_18")
        self.gridLayout_5.addWidget(self.IP_label_18, 7, 0, 1, 1)
        self.IP_edit_18 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_18.setObjectName("IP_edit_18")
        self.gridLayout_5.addWidget(self.IP_edit_18, 7, 1, 1, 1)
        self.IP_label_19 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_19.setText("")
        self.IP_label_19.setScaledContents(True)
        self.IP_label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_19.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_19.setObjectName("IP_label_19")
        self.gridLayout_5.addWidget(self.IP_label_19, 8, 0, 1, 1)
        self.IP_edit_19 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_19.setObjectName("IP_edit_19")
        self.gridLayout_5.addWidget(self.IP_edit_19, 8, 1, 1, 1)
        self.IP_label_20 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_20.setText("")
        self.IP_label_20.setScaledContents(True)
        self.IP_label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_20.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_20.setObjectName("IP_label_20")
        self.gridLayout_5.addWidget(self.IP_label_20, 9, 0, 1, 1)
        self.IP_edit_20 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_20.setObjectName("IP_edit_20")
        self.gridLayout_5.addWidget(self.IP_edit_20, 9, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_5)
        self.line_2 = QtWidgets.QFrame(self.frame_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.IP_label_21 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_21.setText("")
        self.IP_label_21.setScaledContents(True)
        self.IP_label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_21.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_21.setObjectName("IP_label_21")
        self.gridLayout_6.addWidget(self.IP_label_21, 0, 0, 1, 1)
        self.IP_edit_21 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_21.setObjectName("IP_edit_21")
        self.gridLayout_6.addWidget(self.IP_edit_21, 0, 1, 1, 1)
        self.IP_label_22 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_22.setText("")
        self.IP_label_22.setScaledContents(True)
        self.IP_label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_22.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_22.setObjectName("IP_label_22")
        self.gridLayout_6.addWidget(self.IP_label_22, 1, 0, 1, 1)
        self.IP_edit_22 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_22.setObjectName("IP_edit_22")
        self.gridLayout_6.addWidget(self.IP_edit_22, 1, 1, 1, 1)
        self.IP_label_23 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_23.setText("")
        self.IP_label_23.setScaledContents(True)
        self.IP_label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_23.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_23.setObjectName("IP_label_23")
        self.gridLayout_6.addWidget(self.IP_label_23, 2, 0, 1, 1)
        self.IP_edit_23 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_23.setObjectName("IP_edit_23")
        self.gridLayout_6.addWidget(self.IP_edit_23, 2, 1, 1, 1)
        self.IP_label_24 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_24.setText("")
        self.IP_label_24.setScaledContents(True)
        self.IP_label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_24.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_24.setObjectName("IP_label_24")
        self.gridLayout_6.addWidget(self.IP_label_24, 3, 0, 1, 1)
        self.IP_edit_24 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_24.setObjectName("IP_edit_24")
        self.gridLayout_6.addWidget(self.IP_edit_24, 3, 1, 1, 1)
        self.IP_label_25 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_25.setText("")
        self.IP_label_25.setScaledContents(True)
        self.IP_label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_25.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_25.setObjectName("IP_label_25")
        self.gridLayout_6.addWidget(self.IP_label_25, 4, 0, 1, 1)
        self.IP_edit_25 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_25.setObjectName("IP_edit_25")
        self.gridLayout_6.addWidget(self.IP_edit_25, 4, 1, 1, 1)
        self.IP_label_26 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_26.setText("")
        self.IP_label_26.setScaledContents(True)
        self.IP_label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_26.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_26.setObjectName("IP_label_26")
        self.gridLayout_6.addWidget(self.IP_label_26, 5, 0, 1, 1)
        self.IP_edit_26 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_26.setObjectName("IP_edit_26")
        self.gridLayout_6.addWidget(self.IP_edit_26, 5, 1, 1, 1)
        self.IP_label_27 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_27.setText("")
        self.IP_label_27.setScaledContents(True)
        self.IP_label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_27.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_27.setObjectName("IP_label_27")
        self.gridLayout_6.addWidget(self.IP_label_27, 6, 0, 1, 1)
        self.IP_edit_27 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_27.setObjectName("IP_edit_27")
        self.gridLayout_6.addWidget(self.IP_edit_27, 6, 1, 1, 1)
        self.IP_label_28 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_28.setText("")
        self.IP_label_28.setScaledContents(True)
        self.IP_label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_28.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_28.setObjectName("IP_label_28")
        self.gridLayout_6.addWidget(self.IP_label_28, 7, 0, 1, 1)
        self.IP_edit_28 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_28.setObjectName("IP_edit_28")
        self.gridLayout_6.addWidget(self.IP_edit_28, 7, 1, 1, 1)
        self.IP_label_29 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_29.setText("")
        self.IP_label_29.setScaledContents(True)
        self.IP_label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_29.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_29.setObjectName("IP_label_29")
        self.gridLayout_6.addWidget(self.IP_label_29, 8, 0, 1, 1)
        self.IP_edit_29 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_29.setObjectName("IP_edit_29")
        self.gridLayout_6.addWidget(self.IP_edit_29, 8, 1, 1, 1)
        self.IP_label_30 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_30.setText("")
        self.IP_label_30.setScaledContents(True)
        self.IP_label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_30.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_30.setObjectName("IP_label_30")
        self.gridLayout_6.addWidget(self.IP_label_30, 9, 0, 1, 1)
        self.IP_edit_30 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_30.setObjectName("IP_edit_30")
        self.gridLayout_6.addWidget(self.IP_edit_30, 9, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_6)
        self.line_5 = QtWidgets.QFrame(self.frame_2)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_2.addWidget(self.line_5)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.IP_label_31 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_31.setText("")
        self.IP_label_31.setScaledContents(True)
        self.IP_label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_31.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_31.setObjectName("IP_label_31")
        self.gridLayout_11.addWidget(self.IP_label_31, 0, 0, 1, 1)
        self.IP_edit_31 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_31.setObjectName("IP_edit_31")
        self.gridLayout_11.addWidget(self.IP_edit_31, 0, 1, 1, 1)
        self.IP_label_32 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_32.setText("")
        self.IP_label_32.setScaledContents(True)
        self.IP_label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_32.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_32.setObjectName("IP_label_32")
        self.gridLayout_11.addWidget(self.IP_label_32, 1, 0, 1, 1)
        self.IP_edit_32 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_32.setObjectName("IP_edit_32")
        self.gridLayout_11.addWidget(self.IP_edit_32, 1, 1, 1, 1)
        self.IP_label_33 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_33.setText("")
        self.IP_label_33.setScaledContents(True)
        self.IP_label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_33.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_33.setObjectName("IP_label_33")
        self.gridLayout_11.addWidget(self.IP_label_33, 2, 0, 1, 1)
        self.IP_edit_33 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_33.setObjectName("IP_edit_33")
        self.gridLayout_11.addWidget(self.IP_edit_33, 2, 1, 1, 1)
        self.IP_label_34 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_34.setText("")
        self.IP_label_34.setScaledContents(True)
        self.IP_label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_34.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_34.setObjectName("IP_label_34")
        self.gridLayout_11.addWidget(self.IP_label_34, 3, 0, 1, 1)
        self.IP_edit_34 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_34.setObjectName("IP_edit_34")
        self.gridLayout_11.addWidget(self.IP_edit_34, 3, 1, 1, 1)
        self.IP_label_35 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_35.setText("")
        self.IP_label_35.setScaledContents(True)
        self.IP_label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_35.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_35.setObjectName("IP_label_35")
        self.gridLayout_11.addWidget(self.IP_label_35, 4, 0, 1, 1)
        self.IP_edit_35 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_35.setObjectName("IP_edit_35")
        self.gridLayout_11.addWidget(self.IP_edit_35, 4, 1, 1, 1)
        self.IP_label_36 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_36.setText("")
        self.IP_label_36.setScaledContents(True)
        self.IP_label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_36.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_36.setObjectName("IP_label_36")
        self.gridLayout_11.addWidget(self.IP_label_36, 5, 0, 1, 1)
        self.IP_edit_36 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_36.setObjectName("IP_edit_36")
        self.gridLayout_11.addWidget(self.IP_edit_36, 5, 1, 1, 1)
        self.IP_label_37 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_37.setText("")
        self.IP_label_37.setScaledContents(True)
        self.IP_label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_37.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_37.setObjectName("IP_label_37")
        self.gridLayout_11.addWidget(self.IP_label_37, 6, 0, 1, 1)
        self.IP_edit_37 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_37.setObjectName("IP_edit_37")
        self.gridLayout_11.addWidget(self.IP_edit_37, 6, 1, 1, 1)
        self.IP_label_38 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_38.setText("")
        self.IP_label_38.setScaledContents(True)
        self.IP_label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_38.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_38.setObjectName("IP_label_38")
        self.gridLayout_11.addWidget(self.IP_label_38, 7, 0, 1, 1)
        self.IP_edit_38 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_38.setObjectName("IP_edit_38")
        self.gridLayout_11.addWidget(self.IP_edit_38, 7, 1, 1, 1)
        self.IP_label_39 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_39.setText("")
        self.IP_label_39.setScaledContents(True)
        self.IP_label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_39.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_39.setObjectName("IP_label_39")
        self.gridLayout_11.addWidget(self.IP_label_39, 8, 0, 1, 1)
        self.IP_edit_39 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_39.setObjectName("IP_edit_39")
        self.gridLayout_11.addWidget(self.IP_edit_39, 8, 1, 1, 1)
        self.IP_label_40 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_40.setText("")
        self.IP_label_40.setScaledContents(True)
        self.IP_label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_40.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_40.setObjectName("IP_label_40")
        self.gridLayout_11.addWidget(self.IP_label_40, 9, 0, 1, 1)
        self.IP_edit_40 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_40.setObjectName("IP_edit_40")
        self.gridLayout_11.addWidget(self.IP_edit_40, 9, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_11)
        self.line_4 = QtWidgets.QFrame(self.frame_2)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_2.addWidget(self.line_4)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.IP_label_41 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_41.setText("")
        self.IP_label_41.setScaledContents(True)
        self.IP_label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_41.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_41.setObjectName("IP_label_41")
        self.gridLayout_12.addWidget(self.IP_label_41, 0, 0, 1, 1)
        self.IP_edit_41 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_41.setObjectName("IP_edit_41")
        self.gridLayout_12.addWidget(self.IP_edit_41, 0, 1, 1, 1)
        self.IP_label_42 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_42.setText("")
        self.IP_label_42.setScaledContents(True)
        self.IP_label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_42.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_42.setObjectName("IP_label_42")
        self.gridLayout_12.addWidget(self.IP_label_42, 1, 0, 1, 1)
        self.IP_edit_42 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_42.setObjectName("IP_edit_42")
        self.gridLayout_12.addWidget(self.IP_edit_42, 1, 1, 1, 1)
        self.IP_label_43 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_43.setText("")
        self.IP_label_43.setScaledContents(True)
        self.IP_label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_43.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_43.setObjectName("IP_label_43")
        self.gridLayout_12.addWidget(self.IP_label_43, 2, 0, 1, 1)
        self.IP_edit_43 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_43.setObjectName("IP_edit_43")
        self.gridLayout_12.addWidget(self.IP_edit_43, 2, 1, 1, 1)
        self.IP_label_44 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_44.setText("")
        self.IP_label_44.setScaledContents(True)
        self.IP_label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_44.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_44.setObjectName("IP_label_44")
        self.gridLayout_12.addWidget(self.IP_label_44, 3, 0, 1, 1)
        self.IP_edit_44 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_44.setObjectName("IP_edit_44")
        self.gridLayout_12.addWidget(self.IP_edit_44, 3, 1, 1, 1)
        self.IP_label_45 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_45.setText("")
        self.IP_label_45.setScaledContents(True)
        self.IP_label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_45.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_45.setObjectName("IP_label_45")
        self.gridLayout_12.addWidget(self.IP_label_45, 4, 0, 1, 1)
        self.IP_edit_45 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_45.setObjectName("IP_edit_45")
        self.gridLayout_12.addWidget(self.IP_edit_45, 4, 1, 1, 1)
        self.IP_label_46 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_46.setText("")
        self.IP_label_46.setScaledContents(True)
        self.IP_label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_46.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_46.setObjectName("IP_label_46")
        self.gridLayout_12.addWidget(self.IP_label_46, 5, 0, 1, 1)
        self.IP_edit_46 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_46.setObjectName("IP_edit_46")
        self.gridLayout_12.addWidget(self.IP_edit_46, 5, 1, 1, 1)
        self.IP_label_47 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_47.setText("")
        self.IP_label_47.setScaledContents(True)
        self.IP_label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_47.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_47.setObjectName("IP_label_47")
        self.gridLayout_12.addWidget(self.IP_label_47, 6, 0, 1, 1)
        self.IP_edit_47 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_47.setObjectName("IP_edit_47")
        self.gridLayout_12.addWidget(self.IP_edit_47, 6, 1, 1, 1)
        self.IP_label_48 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_48.setText("")
        self.IP_label_48.setScaledContents(True)
        self.IP_label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_48.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_48.setObjectName("IP_label_48")
        self.gridLayout_12.addWidget(self.IP_label_48, 7, 0, 1, 1)
        self.IP_edit_48 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_48.setObjectName("IP_edit_48")
        self.gridLayout_12.addWidget(self.IP_edit_48, 7, 1, 1, 1)
        self.IP_label_49 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_49.setText("")
        self.IP_label_49.setScaledContents(True)
        self.IP_label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_49.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_49.setObjectName("IP_label_49")
        self.gridLayout_12.addWidget(self.IP_label_49, 8, 0, 1, 1)
        self.IP_edit_49 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_49.setObjectName("IP_edit_49")
        self.gridLayout_12.addWidget(self.IP_edit_49, 8, 1, 1, 1)
        self.IP_label_50 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_50.setText("")
        self.IP_label_50.setScaledContents(True)
        self.IP_label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_50.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_50.setObjectName("IP_label_50")
        self.gridLayout_12.addWidget(self.IP_label_50, 9, 0, 1, 1)
        self.IP_edit_50 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_50.setObjectName("IP_edit_50")
        self.gridLayout_12.addWidget(self.IP_edit_50, 9, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_12)
        self.line_3 = QtWidgets.QFrame(self.frame_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_2.addWidget(self.line_3)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.IP_label_51 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_51.setText("")
        self.IP_label_51.setScaledContents(True)
        self.IP_label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_51.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_51.setObjectName("IP_label_51")
        self.gridLayout_13.addWidget(self.IP_label_51, 0, 0, 1, 1)
        self.IP_edit_51 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_51.setObjectName("IP_edit_51")
        self.gridLayout_13.addWidget(self.IP_edit_51, 0, 1, 1, 1)
        self.IP_label_52 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_52.setText("")
        self.IP_label_52.setScaledContents(True)
        self.IP_label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_52.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_52.setObjectName("IP_label_52")
        self.gridLayout_13.addWidget(self.IP_label_52, 1, 0, 1, 1)
        self.IP_edit_52 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_52.setObjectName("IP_edit_52")
        self.gridLayout_13.addWidget(self.IP_edit_52, 1, 1, 1, 1)
        self.IP_label_53 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_53.setText("")
        self.IP_label_53.setScaledContents(True)
        self.IP_label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_53.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_53.setObjectName("IP_label_53")
        self.gridLayout_13.addWidget(self.IP_label_53, 2, 0, 1, 1)
        self.IP_edit_53 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_53.setObjectName("IP_edit_53")
        self.gridLayout_13.addWidget(self.IP_edit_53, 2, 1, 1, 1)
        self.IP_label_54 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_54.setText("")
        self.IP_label_54.setScaledContents(True)
        self.IP_label_54.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_54.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_54.setObjectName("IP_label_54")
        self.gridLayout_13.addWidget(self.IP_label_54, 3, 0, 1, 1)
        self.IP_edit_54 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_54.setObjectName("IP_edit_54")
        self.gridLayout_13.addWidget(self.IP_edit_54, 3, 1, 1, 1)
        self.IP_label_55 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_55.setText("")
        self.IP_label_55.setScaledContents(True)
        self.IP_label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_55.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_55.setObjectName("IP_label_55")
        self.gridLayout_13.addWidget(self.IP_label_55, 4, 0, 1, 1)
        self.IP_edit_55 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_55.setObjectName("IP_edit_55")
        self.gridLayout_13.addWidget(self.IP_edit_55, 4, 1, 1, 1)
        self.IP_label_56 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_56.setText("")
        self.IP_label_56.setScaledContents(True)
        self.IP_label_56.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_56.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_56.setObjectName("IP_label_56")
        self.gridLayout_13.addWidget(self.IP_label_56, 5, 0, 1, 1)
        self.IP_edit_56 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_56.setObjectName("IP_edit_56")
        self.gridLayout_13.addWidget(self.IP_edit_56, 5, 1, 1, 1)
        self.IP_label_57 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_57.setText("")
        self.IP_label_57.setScaledContents(True)
        self.IP_label_57.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_57.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_57.setObjectName("IP_label_57")
        self.gridLayout_13.addWidget(self.IP_label_57, 6, 0, 1, 1)
        self.IP_edit_57 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_57.setObjectName("IP_edit_57")
        self.gridLayout_13.addWidget(self.IP_edit_57, 6, 1, 1, 1)
        self.IP_label_58 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_58.setText("")
        self.IP_label_58.setScaledContents(True)
        self.IP_label_58.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_58.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_58.setObjectName("IP_label_58")
        self.gridLayout_13.addWidget(self.IP_label_58, 7, 0, 1, 1)
        self.IP_edit_58 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_58.setObjectName("IP_edit_58")
        self.gridLayout_13.addWidget(self.IP_edit_58, 7, 1, 1, 1)
        self.IP_label_59 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_59.setText("")
        self.IP_label_59.setScaledContents(True)
        self.IP_label_59.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_59.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_59.setObjectName("IP_label_59")
        self.gridLayout_13.addWidget(self.IP_label_59, 8, 0, 1, 1)
        self.IP_edit_59 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_59.setObjectName("IP_edit_59")
        self.gridLayout_13.addWidget(self.IP_edit_59, 8, 1, 1, 1)
        self.IP_label_60 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_60.setText("")
        self.IP_label_60.setScaledContents(True)
        self.IP_label_60.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_60.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_60.setObjectName("IP_label_60")
        self.gridLayout_13.addWidget(self.IP_label_60, 9, 0, 1, 1)
        self.IP_edit_60 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_60.setObjectName("IP_edit_60")
        self.gridLayout_13.addWidget(self.IP_edit_60, 9, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_13)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.IP_edit_61 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_61.setObjectName("IP_edit_61")
        self.gridLayout_14.addWidget(self.IP_edit_61, 0, 1, 1, 1)
        self.IP_label_61 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_61.setText("")
        self.IP_label_61.setScaledContents(True)
        self.IP_label_61.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_61.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_61.setObjectName("IP_label_61")
        self.gridLayout_14.addWidget(self.IP_label_61, 0, 0, 1, 1)
        self.IP_label_62 = QtWidgets.QLabel(self.frame_2)
        self.IP_label_62.setText("")
        self.IP_label_62.setScaledContents(True)
        self.IP_label_62.setAlignment(QtCore.Qt.AlignCenter)
        self.IP_label_62.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.IP_label_62.setObjectName("IP_label_62")
        self.gridLayout_14.addWidget(self.IP_label_62, 1, 0, 1, 1)
        self.IP_edit_62 = QtWidgets.QLineEdit(self.frame_2)
        self.IP_edit_62.setObjectName("IP_edit_62")
        self.gridLayout_14.addWidget(self.IP_edit_62, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_14)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_4.addWidget(self.frame_2, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.internal_properties_wid, "")
        self.tags_wid = QtWidgets.QWidget()
        self.tags_wid.setObjectName("tags_wid")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tags_wid)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.frame_4 = QtWidgets.QFrame(self.tags_wid)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_7.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_7.setSpacing(4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.grid = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grid.sizePolicy().hasHeightForWidth())
        self.grid.setSizePolicy(sizePolicy)
        self.grid.setFrameShape(QtWidgets.QFrame.Box)
        self.grid.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.grid.setObjectName("grid")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.grid)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setHorizontalSpacing(2)
        self.gridLayout_10.setVerticalSpacing(4)
        self.gridLayout_10.setObjectName("gridLayout_10")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem1, 17, 2, 1, 1)
        self.label_131 = QtWidgets.QLabel(self.grid)
        self.label_131.setMinimumSize(QtCore.QSize(128, 0))
        self.label_131.setObjectName("label_131")
        self.gridLayout_10.addWidget(self.label_131, 3, 1, 1, 1)
        self.lineEdit_art_13 = QtWidgets.QLineEdit(self.grid)
        self.lineEdit_art_13.setObjectName("lineEdit_art_13")
        self.gridLayout_10.addWidget(self.lineEdit_art_13, 0, 2, 1, 1)
        self.label_129 = QtWidgets.QLabel(self.grid)
        self.label_129.setMinimumSize(QtCore.QSize(128, 0))
        self.label_129.setObjectName("label_129")
        self.gridLayout_10.addWidget(self.label_129, 1, 1, 1, 1)
        self.lineEdit_alb_13 = QtWidgets.QLineEdit(self.grid)
        self.lineEdit_alb_13.setObjectName("lineEdit_alb_13")
        self.gridLayout_10.addWidget(self.lineEdit_alb_13, 3, 2, 1, 1)
        self.label_130 = QtWidgets.QLabel(self.grid)
        self.label_130.setMinimumSize(QtCore.QSize(128, 0))
        self.label_130.setObjectName("label_130")
        self.gridLayout_10.addWidget(self.label_130, 2, 1, 1, 1)
        self.lineEdit_alb_a_13 = QtWidgets.QLineEdit(self.grid)
        self.lineEdit_alb_a_13.setObjectName("lineEdit_alb_a_13")
        self.gridLayout_10.addWidget(self.lineEdit_alb_a_13, 2, 2, 1, 1)
        self.label_128 = QtWidgets.QLabel(self.grid)
        self.label_128.setMinimumSize(QtCore.QSize(128, 0))
        self.label_128.setObjectName("label_128")
        self.gridLayout_10.addWidget(self.label_128, 0, 1, 1, 1)
        self.lineEdit_tit_13 = QtWidgets.QLineEdit(self.grid)
        self.lineEdit_tit_13.setObjectName("lineEdit_tit_13")
        self.gridLayout_10.addWidget(self.lineEdit_tit_13, 1, 2, 1, 1)
        self.label_132 = QtWidgets.QLabel(self.grid)
        self.label_132.setMinimumSize(QtCore.QSize(128, 0))
        self.label_132.setObjectName("label_132")
        self.gridLayout_10.addWidget(self.label_132, 4, 1, 1, 1)
        self.lineEdit_gen_13 = QtWidgets.QLineEdit(self.grid)
        self.lineEdit_gen_13.setObjectName("lineEdit_gen_13")
        self.gridLayout_10.addWidget(self.lineEdit_gen_13, 4, 2, 1, 1)
        self.label_133 = QtWidgets.QLabel(self.grid)
        self.label_133.setMinimumSize(QtCore.QSize(128, 0))
        self.label_133.setObjectName("label_133")
        self.gridLayout_10.addWidget(self.label_133, 5, 1, 1, 1)
        self.label_135 = QtWidgets.QLabel(self.grid)
        self.label_135.setMinimumSize(QtCore.QSize(128, 0))
        self.label_135.setObjectName("label_135")
        self.gridLayout_10.addWidget(self.label_135, 7, 1, 1, 1)
        self.label_136 = QtWidgets.QLabel(self.grid)
        self.label_136.setMinimumSize(QtCore.QSize(128, 0))
        self.label_136.setObjectName("label_136")
        self.gridLayout_10.addWidget(self.label_136, 8, 1, 1, 1)
        self.lineEdit_comp_10 = QtWidgets.QLineEdit(self.grid)
        self.lineEdit_comp_10.setObjectName("lineEdit_comp_10")
        self.gridLayout_10.addWidget(self.lineEdit_comp_10, 5, 2, 1, 1)
        self.lineEdit_dur_10 = QtWidgets.QLineEdit(self.grid)
        self.lineEdit_dur_10.setObjectName("lineEdit_dur_10")
        self.gridLayout_10.addWidget(self.lineEdit_dur_10, 6, 2, 1, 1)
        self.label_144 = QtWidgets.QLabel(self.grid)
        self.label_144.setMinimumSize(QtCore.QSize(128, 0))
        self.label_144.setObjectName("label_144")
        self.gridLayout_10.addWidget(self.label_144, 16, 1, 1, 1)
        self.label_134 = QtWidgets.QLabel(self.grid)
        self.label_134.setMinimumSize(QtCore.QSize(128, 0))
        self.label_134.setObjectName("label_134")
        self.gridLayout_10.addWidget(self.label_134, 6, 1, 1, 1)
        self.lineEdit_tra_2 = QtWidgets.QLineEdit(self.grid)
        self.lineEdit_tra_2.setObjectName("lineEdit_tra_2")
        self.gridLayout_10.addWidget(self.lineEdit_tra_2, 14, 2, 1, 1)
        self.lineEdit_dist_2 = QtWidgets.QLineEdit(self.grid)
        self.lineEdit_dist_2.setObjectName("lineEdit_dist_2")
        self.gridLayout_10.addWidget(self.lineEdit_dist_2, 13, 2, 1, 1)
        self.lineEdit_bitr_10 = QtWidgets.QLineEdit(self.grid)
        self.lineEdit_bitr_10.setObjectName("lineEdit_bitr_10")
        self.gridLayout_10.addWidget(self.lineEdit_bitr_10, 8, 2, 1, 1)
        self.label_142 = QtWidgets.QLabel(self.grid)
        self.label_142.setMinimumSize(QtCore.QSize(128, 0))
        self.label_142.setObjectName("label_142")
        self.gridLayout_10.addWidget(self.label_142, 14, 1, 1, 1)
        self.label_141 = QtWidgets.QLabel(self.grid)
        self.label_141.setMinimumSize(QtCore.QSize(128, 0))
        self.label_141.setObjectName("label_141")
        self.gridLayout_10.addWidget(self.label_141, 13, 1, 1, 1)
        self.label_138 = QtWidgets.QLabel(self.grid)
        self.label_138.setMinimumSize(QtCore.QSize(128, 0))
        self.label_138.setObjectName("label_138")
        self.gridLayout_10.addWidget(self.label_138, 10, 1, 1, 1)
        self.lineEdit_off_10 = QtWidgets.QLineEdit(self.grid)
        self.lineEdit_off_10.setObjectName("lineEdit_off_10")
        self.gridLayout_10.addWidget(self.lineEdit_off_10, 7, 2, 1, 1)
        self.label_139 = QtWidgets.QLabel(self.grid)
        self.label_139.setMinimumSize(QtCore.QSize(128, 0))
        self.label_139.setObjectName("label_139")
        self.gridLayout_10.addWidget(self.label_139, 11, 1, 1, 1)
        self.lineEdit_dis_2 = QtWidgets.QLineEdit(self.grid)
        self.lineEdit_dis_2.setObjectName("lineEdit_dis_2")
        self.gridLayout_10.addWidget(self.lineEdit_dis_2, 12, 2, 1, 1)
        self.lineEdit_chnl_10 = QtWidgets.QLineEdit(self.grid)
        self.lineEdit_chnl_10.setObjectName("lineEdit_chnl_10")
        self.gridLayout_10.addWidget(self.lineEdit_chnl_10, 9, 2, 1, 1)
        self.lineEdit_sr_2 = QtWidgets.QLineEdit(self.grid)
        self.lineEdit_sr_2.setObjectName("lineEdit_sr_2")
        self.gridLayout_10.addWidget(self.lineEdit_sr_2, 11, 2, 1, 1)
        self.lineEdit_traT_2 = QtWidgets.QLineEdit(self.grid)
        self.lineEdit_traT_2.setObjectName("lineEdit_traT_2")
        self.gridLayout_10.addWidget(self.lineEdit_traT_2, 15, 2, 1, 1)
        self.lineEdit_yr_2 = QtWidgets.QLineEdit(self.grid)
        self.lineEdit_yr_2.setObjectName("lineEdit_yr_2")
        self.gridLayout_10.addWidget(self.lineEdit_yr_2, 16, 2, 1, 1)
        self.label_143 = QtWidgets.QLabel(self.grid)
        self.label_143.setMinimumSize(QtCore.QSize(128, 0))
        self.label_143.setObjectName("label_143")
        self.gridLayout_10.addWidget(self.label_143, 15, 1, 1, 1)
        self.label_137 = QtWidgets.QLabel(self.grid)
        self.label_137.setMinimumSize(QtCore.QSize(128, 0))
        self.label_137.setObjectName("label_137")
        self.gridLayout_10.addWidget(self.label_137, 9, 1, 1, 1)
        self.label_140 = QtWidgets.QLabel(self.grid)
        self.label_140.setMinimumSize(QtCore.QSize(128, 0))
        self.label_140.setObjectName("label_140")
        self.gridLayout_10.addWidget(self.label_140, 12, 1, 1, 1)
        self.lineEdit_fs_2 = QtWidgets.QLineEdit(self.grid)
        self.lineEdit_fs_2.setObjectName("lineEdit_fs_2")
        self.gridLayout_10.addWidget(self.lineEdit_fs_2, 10, 2, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.grid)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_9.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_9.setHorizontalSpacing(1)
        self.gridLayout_9.setVerticalSpacing(2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_9.addWidget(self.pushButton_4, 3, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_9.addWidget(self.pushButton_2, 3, 1, 1, 2)
        self.lineEdit_63_web = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_63_web.setObjectName("lineEdit_63_web")
        self.gridLayout_9.addWidget(self.lineEdit_63_web, 3, 3, 1, 2)
        self.Cover_image_pix = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.Cover_image_pix.sizePolicy().hasHeightForWidth())
        self.Cover_image_pix.setSizePolicy(sizePolicy)
        self.Cover_image_pix.setMinimumSize(QtCore.QSize(300, 250))
        self.Cover_image_pix.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Cover_image_pix.setFrameShape(QtWidgets.QFrame.Box)
        self.Cover_image_pix.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Cover_image_pix.setText("")
        self.Cover_image_pix.setScaledContents(True)
        self.Cover_image_pix.setObjectName("Cover_image_pix")
        self.gridLayout_9.addWidget(self.Cover_image_pix, 1, 0, 1, 5)
        self.pushButton_Findcov = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_Findcov.setObjectName("pushButton_Findcov")
        self.gridLayout_9.addWidget(self.pushButton_Findcov, 0, 4, 1, 1)
        self.comboBox_cover = QtWidgets.QComboBox(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_cover.sizePolicy().hasHeightForWidth())
        self.comboBox_cover.setSizePolicy(sizePolicy)
        self.comboBox_cover.setObjectName("comboBox_cover")
        self.gridLayout_9.addWidget(self.comboBox_cover, 0, 0, 1, 2)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_9.addWidget(self.pushButton_5, 0, 2, 1, 2)
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_9.addWidget(self.textBrowser, 2, 0, 1, 5)
        self.gridLayout_10.addWidget(self.frame_5, 0, 0, 18, 1)
        self.gridLayout_7.addWidget(self.grid, 2, 0, 1, 1)
        self.gridLayout_8.addWidget(self.frame_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tags_wid, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.pushButton_6)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout.addWidget(self.pushButton_7)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 720, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.internal_properties_wid), _translate("MainWindow", "Internal Properties"))
        self.label_131.setText(_translate("MainWindow", "Album"))
        self.label_129.setText(_translate("MainWindow", "Title"))
        self.label_130.setText(_translate("MainWindow", "Album Artist"))
        self.label_128.setText(_translate("MainWindow", "Artist"))
        self.label_132.setText(_translate("MainWindow", "Genre"))
        self.label_133.setText(_translate("MainWindow", "Composer"))
        self.label_135.setText(_translate("MainWindow", "Offset"))
        self.label_136.setText(_translate("MainWindow", "Bitrate"))
        self.label_144.setText(_translate("MainWindow", "Year"))
        self.label_134.setText(_translate("MainWindow", "Duration"))
        self.label_142.setText(_translate("MainWindow", "Track"))
        self.label_141.setText(_translate("MainWindow", "Disc Total"))
        self.label_138.setText(_translate("MainWindow", "File Size"))
        self.label_139.setText(_translate("MainWindow", "Samplerate"))
        self.label_143.setText(_translate("MainWindow", "Track Total"))
        self.label_137.setText(_translate("MainWindow", "Channel"))
        self.label_140.setText(_translate("MainWindow", "Disc"))
        self.pushButton_4.setText(_translate("MainWindow", "Delete Lyrics"))
        self.pushButton_2.setText(_translate("MainWindow", "Find Lyrics"))
        self.lineEdit_63_web.setText(_translate("MainWindow", "Enter Website"))
        self.pushButton_Findcov.setText(_translate("MainWindow", "Find Cover"))
        self.pushButton_5.setText(_translate("MainWindow", "Auto Tag"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tags_wid), _translate("MainWindow", "Tags"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_6.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_7.setText(_translate("MainWindow", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
