# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_forms\file_explorer.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_file_exp(object):
    def setupUi(self, MainWindow_file_exp):
        MainWindow_file_exp.setObjectName("MainWindow_file_exp")
        MainWindow_file_exp.setWindowModality(QtCore.Qt.NonModal)
        MainWindow_file_exp.setEnabled(True)
        MainWindow_file_exp.resize(739, 553)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow_file_exp.sizePolicy().hasHeightForWidth())
        MainWindow_file_exp.setSizePolicy(sizePolicy)
        MainWindow_file_exp.setMaximumSize(QtCore.QSize(6120, 3000))
        MainWindow_file_exp.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\ui_forms\\../../../.designer/backup/resources/file_explorer/icons8-sound-wave-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow_file_exp.setWindowIcon(icon)
        MainWindow_file_exp.setWindowOpacity(1.0)
        MainWindow_file_exp.setAutoFillBackground(False)
        MainWindow_file_exp.setIconSize(QtCore.QSize(24, 24))
        MainWindow_file_exp.setDocumentMode(False)
        MainWindow_file_exp.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow_file_exp.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow_file_exp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(10, 2, 10, 6)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.grid = QtWidgets.QFrame(self.centralwidget)
        self.grid.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.grid.setObjectName("grid")
        self.gridLayout = QtWidgets.QGridLayout(self.grid)
        self.gridLayout.setContentsMargins(4, 4, 4, 4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.listView = QtWidgets.QListView(self.grid)
        self.listView.setAutoFillBackground(True)
        self.listView.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.listView.setAlternatingRowColors(False)
        self.listView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.listView.setObjectName("listView")
        self.gridLayout.addWidget(self.listView, 0, 1, 1, 2)
        self.treeView = QtWidgets.QTreeView(self.grid)
        self.treeView.setMouseTracking(False)
        self.treeView.setAutoFillBackground(True)
        self.treeView.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.treeView.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.treeView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.treeView.setProperty("showDropIndicator", False)
        self.treeView.setDragEnabled(False)
        self.treeView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.treeView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.treeView.setAutoExpandDelay(1)
        self.treeView.setIndentation(15)
        self.treeView.setUniformRowHeights(True)
        self.treeView.setSortingEnabled(True)
        self.treeView.setAllColumnsShowFocus(True)
        self.treeView.setWordWrap(True)
        self.treeView.setHeaderHidden(False)
        self.treeView.setObjectName("treeView")
        self.treeView.header().setCascadingSectionResizes(True)
        self.treeView.header().setDefaultSectionSize(120)
        self.treeView.header().setHighlightSections(False)
        self.gridLayout.addWidget(self.treeView, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_12 = QtWidgets.QLabel(self.grid)
        self.label_12.setEnabled(False)
        self.label_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_12.setText("")
        self.label_12.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout.addWidget(self.label_12)
        self.pushButton = QtWidgets.QPushButton(self.grid)
        self.pushButton.setMaximumSize(QtCore.QSize(74, 16777215))
        self.pushButton.setCheckable(False)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.grid)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setAutoFillBackground(False)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 0, 1, 3)
        self.gridLayout_2.addWidget(self.grid, 0, 0, 1, 1)
        MainWindow_file_exp.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow_file_exp)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_file_exp)

    def retranslateUi(self, MainWindow_file_exp):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_file_exp.setWindowTitle(_translate("MainWindow_file_exp", "File Explorer"))
        self.pushButton.setText(_translate("MainWindow_file_exp", "Scan"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow_file_exp = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_file_exp()
    ui.setupUi(MainWindow_file_exp)
    MainWindow_file_exp.show()
    sys.exit(app.exec_())
