# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 745)
        MainWindow.setMinimumSize(QtCore.QSize(945, 662))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_2.setSpacing(1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setObjectName("tabWidget")
        self.music = QtWidgets.QWidget()
        self.music.setObjectName("music")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.music)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSpacing(2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableView_music = QtWidgets.QTableView(self.music)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableView_music.setFont(font)
        self.tableView_music.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableView_music.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView_music.setProperty("showDropIndicator", False)
        self.tableView_music.setDragEnabled(False)
        self.tableView_music.setDragDropOverwriteMode(False)
        self.tableView_music.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableView_music.setAlternatingRowColors(True)
        self.tableView_music.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableView_music.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView_music.setShowGrid(True)
        self.tableView_music.setGridStyle(QtCore.Qt.NoPen)
        self.tableView_music.setSortingEnabled(True)
        self.tableView_music.setWordWrap(False)
        self.tableView_music.setCornerButtonEnabled(False)
        self.tableView_music.setObjectName("tableView_music")
        self.tableView_music.verticalHeader().setCascadingSectionResizes(True)
        self.tableView_music.verticalHeader().setDefaultSectionSize(0)
        self.gridLayout_4.addWidget(self.tableView_music, 0, 1, 1, 1)
        self.side_layout_frame = QtWidgets.QFrame(self.music)
        self.side_layout_frame.setObjectName("side_layout_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.side_layout_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.side_layout_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMinimumSize(QtCore.QSize(300, 300))
        self.graphicsView.setMaximumSize(QtCore.QSize(450, 450))
        self.graphicsView.setSizeIncrement(QtCore.QSize(2, 2))
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout.addWidget(self.graphicsView)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listView = QtWidgets.QListView(self.side_layout_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView.sizePolicy().hasHeightForWidth())
        self.listView.setSizePolicy(sizePolicy)
        self.listView.setMaximumSize(QtCore.QSize(300, 16777215))
        self.listView.setObjectName("listView")
        self.horizontalLayout_2.addWidget(self.listView)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout_4.addWidget(self.side_layout_frame, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 2, 0, 1, 1)
        self.top_control_frame = QtWidgets.QFrame(self.music)
        self.top_control_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_control_frame.setObjectName("top_control_frame")
        self.top_control_grid = QtWidgets.QGridLayout(self.top_control_frame)
        self.top_control_grid.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.top_control_grid.setContentsMargins(1, 1, 1, 1)
        self.top_control_grid.setSpacing(1)
        self.top_control_grid.setObjectName("top_control_grid")
        self.toolButton = QtWidgets.QToolButton(self.top_control_frame)
        self.toolButton.setMinimumSize(QtCore.QSize(0, 26))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.toolButton.setFont(font)
        self.toolButton.setCheckable(False)
        self.toolButton.setAutoRaise(False)
        self.toolButton.setObjectName("toolButton")
        self.top_control_grid.addWidget(self.toolButton, 0, 7, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.top_control_grid.addItem(spacerItem, 0, 4, 1, 1)
        self.control_button_frame = QtWidgets.QFrame(self.top_control_frame)
        self.control_button_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.control_button_frame.setObjectName("control_button_frame")
        self.Buttons_2 = QtWidgets.QHBoxLayout(self.control_button_frame)
        self.Buttons_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.Buttons_2.setContentsMargins(0, 0, 0, 0)
        self.Buttons_2.setSpacing(2)
        self.Buttons_2.setObjectName("Buttons_2")
        self.skip_back = QtWidgets.QPushButton(self.control_button_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skip_back.sizePolicy().hasHeightForWidth())
        self.skip_back.setSizePolicy(sizePolicy)
        self.skip_back.setMaximumSize(QtCore.QSize(30, 75))
        self.skip_back.setBaseSize(QtCore.QSize(30, 75))
        self.skip_back.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/icons/noun_rewind_1939969.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.skip_back.setIcon(icon)
        self.skip_back.setFlat(True)
        self.skip_back.setObjectName("skip_back")
        self.Buttons_2.addWidget(self.skip_back)
        self.skip_track_back = QtWidgets.QPushButton(self.control_button_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skip_track_back.sizePolicy().hasHeightForWidth())
        self.skip_track_back.setSizePolicy(sizePolicy)
        self.skip_track_back.setMaximumSize(QtCore.QSize(30, 75))
        self.skip_track_back.setBaseSize(QtCore.QSize(30, 75))
        self.skip_track_back.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resources/icons/noun_previous_1939964.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.skip_track_back.setIcon(icon1)
        self.skip_track_back.setFlat(True)
        self.skip_track_back.setObjectName("skip_track_back")
        self.Buttons_2.addWidget(self.skip_track_back)
        self.stop = QtWidgets.QPushButton(self.control_button_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop.sizePolicy().hasHeightForWidth())
        self.stop.setSizePolicy(sizePolicy)
        self.stop.setMaximumSize(QtCore.QSize(30, 75))
        self.stop.setBaseSize(QtCore.QSize(30, 75))
        self.stop.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("resources/icons/noun_Stop_219790.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop.setIcon(icon2)
        self.stop.setFlat(True)
        self.stop.setObjectName("stop")
        self.Buttons_2.addWidget(self.stop)
        self.play_button = QtWidgets.QPushButton(self.control_button_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.play_button.sizePolicy().hasHeightForWidth())
        self.play_button.setSizePolicy(sizePolicy)
        self.play_button.setMaximumSize(QtCore.QSize(30, 75))
        self.play_button.setBaseSize(QtCore.QSize(30, 75))
        self.play_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("resources/icons/noun_play_1939965.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play_button.setIcon(icon3)
        self.play_button.setDefault(False)
        self.play_button.setFlat(True)
        self.play_button.setObjectName("play_button")
        self.Buttons_2.addWidget(self.play_button)
        self.pause = QtWidgets.QPushButton(self.control_button_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pause.sizePolicy().hasHeightForWidth())
        self.pause.setSizePolicy(sizePolicy)
        self.pause.setMaximumSize(QtCore.QSize(30, 75))
        self.pause.setBaseSize(QtCore.QSize(30, 75))
        self.pause.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("resources/icons/noun_pause_1939967.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pause.setIcon(icon4)
        self.pause.setFlat(True)
        self.pause.setObjectName("pause")
        self.Buttons_2.addWidget(self.pause)
        self.skip_track_fwd = QtWidgets.QPushButton(self.control_button_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skip_track_fwd.sizePolicy().hasHeightForWidth())
        self.skip_track_fwd.setSizePolicy(sizePolicy)
        self.skip_track_fwd.setMaximumSize(QtCore.QSize(30, 75))
        self.skip_track_fwd.setBaseSize(QtCore.QSize(30, 75))
        self.skip_track_fwd.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("resources/icons/noun_Next_1939966.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.skip_track_fwd.setIcon(icon5)
        self.skip_track_fwd.setFlat(True)
        self.skip_track_fwd.setObjectName("skip_track_fwd")
        self.Buttons_2.addWidget(self.skip_track_fwd)
        self.skip_ford = QtWidgets.QPushButton(self.control_button_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skip_ford.sizePolicy().hasHeightForWidth())
        self.skip_ford.setSizePolicy(sizePolicy)
        self.skip_ford.setMaximumSize(QtCore.QSize(30, 75))
        self.skip_ford.setBaseSize(QtCore.QSize(30, 75))
        self.skip_ford.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("resources/icons/noun_forward_1939968.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.skip_ford.setIcon(icon6)
        self.skip_ford.setFlat(True)
        self.skip_ford.setObjectName("skip_ford")
        self.Buttons_2.addWidget(self.skip_ford)
        self.shuffle_btn = QtWidgets.QPushButton(self.control_button_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shuffle_btn.sizePolicy().hasHeightForWidth())
        self.shuffle_btn.setSizePolicy(sizePolicy)
        self.shuffle_btn.setMaximumSize(QtCore.QSize(30, 75))
        self.shuffle_btn.setBaseSize(QtCore.QSize(30, 75))
        self.shuffle_btn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("resources/icons/noun_Shuffle_1939972.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shuffle_btn.setIcon(icon7)
        self.shuffle_btn.setFlat(True)
        self.shuffle_btn.setObjectName("shuffle_btn")
        self.Buttons_2.addWidget(self.shuffle_btn)
        self.top_control_grid.addWidget(self.control_button_frame, 0, 2, 1, 1)
        self.volume_control_frame = QtWidgets.QFrame(self.top_control_frame)
        self.volume_control_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.volume_control_frame.setObjectName("volume_control_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.volume_control_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.mute_btn = QtWidgets.QPushButton(self.volume_control_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mute_btn.sizePolicy().hasHeightForWidth())
        self.mute_btn.setSizePolicy(sizePolicy)
        self.mute_btn.setMaximumSize(QtCore.QSize(30, 75))
        self.mute_btn.setBaseSize(QtCore.QSize(30, 75))
        self.mute_btn.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("resources/icons/noun_Mute_1939974.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mute_btn.setIcon(icon8)
        self.mute_btn.setFlat(True)
        self.mute_btn.setObjectName("mute_btn")
        self.horizontalLayout_3.addWidget(self.mute_btn)
        self.horizontalSlider = QtWidgets.QSlider(self.volume_control_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider.sizePolicy().hasHeightForWidth())
        self.horizontalSlider.setSizePolicy(sizePolicy)
        self.horizontalSlider.setMaximumSize(QtCore.QSize(80, 16777215))
        self.horizontalSlider.setPageStep(5)
        self.horizontalSlider.setSliderPosition(0)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setInvertedAppearance(False)
        self.horizontalSlider.setInvertedControls(False)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_3.addWidget(self.horizontalSlider)
        self.volume_btn = QtWidgets.QPushButton(self.volume_control_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.volume_btn.sizePolicy().hasHeightForWidth())
        self.volume_btn.setSizePolicy(sizePolicy)
        self.volume_btn.setMaximumSize(QtCore.QSize(30, 75))
        self.volume_btn.setBaseSize(QtCore.QSize(30, 75))
        self.volume_btn.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("resources/icons/noun_Sound_1939979.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.volume_btn.setIcon(icon9)
        self.volume_btn.setFlat(True)
        self.volume_btn.setObjectName("volume_btn")
        self.horizontalLayout_3.addWidget(self.volume_btn)
        self.top_control_grid.addWidget(self.volume_control_frame, 0, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.top_control_frame)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 26))
        self.lineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit.setBaseSize(QtCore.QSize(0, 22))
        self.lineEdit.setMaxLength(50)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.top_control_grid.addWidget(self.lineEdit, 0, 6, 1, 1)
        self.gridLayout_3.addWidget(self.top_control_frame, 0, 0, 1, 1)
        self.bottom_control_fraME = QtWidgets.QFrame(self.music)
        self.bottom_control_fraME.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom_control_fraME.setObjectName("bottom_control_fraME")
        self.horizontal_player_control = QtWidgets.QHBoxLayout(self.bottom_control_fraME)
        self.horizontal_player_control.setContentsMargins(0, 0, 0, 0)
        self.horizontal_player_control.setSpacing(2)
        self.horizontal_player_control.setObjectName("horizontal_player_control")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_player_control.addItem(spacerItem1)
        self.time_dial = QtWidgets.QLabel(self.bottom_control_fraME)
        self.time_dial.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_dial.sizePolicy().hasHeightForWidth())
        self.time_dial.setSizePolicy(sizePolicy)
        self.time_dial.setMaximumSize(QtCore.QSize(55, 16777215))
        self.time_dial.setFrameShape(QtWidgets.QFrame.Box)
        self.time_dial.setObjectName("time_dial")
        self.horizontal_player_control.addWidget(self.time_dial)
        self.gridLayout_3.addWidget(self.bottom_control_fraME, 3, 0, 1, 1)
        self.tabWidget.addTab(self.music, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1366, 21))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        self.menuFiles = QtWidgets.QMenu(self.menubar)
        self.menuFiles.setTearOffEnabled(False)
        self.menuFiles.setSeparatorsCollapsible(False)
        self.menuFiles.setObjectName("menuFiles")
        MainWindow.setMenuBar(self.menubar)
        self.actionAdd_Files_to_librayr = QtWidgets.QAction(MainWindow)
        self.actionAdd_Files_to_librayr.setCheckable(False)
        self.actionAdd_Files_to_librayr.setObjectName("actionAdd_Files_to_librayr")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionRescan = QtWidgets.QAction(MainWindow)
        self.actionRescan.setObjectName("actionRescan")
        self.menuFiles.addAction(self.actionAdd_Files_to_librayr)
        self.menuFiles.addAction(self.actionSettings)
        self.menuFiles.addAction(self.actionRescan)
        self.menubar.addAction(self.menuFiles.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolButton.setText(_translate("MainWindow", "Search"))
        self.toolButton.setShortcut(_translate("MainWindow", "Return"))
        self.lineEdit.setText(_translate("MainWindow", "Search Library"))
        self.time_dial.setText(_translate("MainWindow", "59:59:999"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.music), _translate("MainWindow", "Music"))
        self.menuFiles.setTitle(_translate("MainWindow", "Files"))
        self.actionAdd_Files_to_librayr.setText(_translate("MainWindow", "Add Files to library"))
        self.actionAdd_Files_to_librayr.setShortcut(_translate("MainWindow", "Ins"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionRescan.setText(_translate("MainWindow", "Rescan"))
        self.actionRescan.setShortcut(_translate("MainWindow", "Ctrl+S"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
