# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1065, 735)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_2.setSpacing(1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(900, 600))
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setObjectName("tabWidget")
        self.music = QtWidgets.QWidget()
        self.music.setObjectName("music")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.music)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridFrame = QtWidgets.QFrame(self.music)
        self.gridFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.gridFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.gridFrame.setObjectName("gridFrame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridFrame)
        self.gridLayout_4.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.control_button_frame = QtWidgets.QFrame(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.control_button_frame.sizePolicy().hasHeightForWidth())
        self.control_button_frame.setSizePolicy(sizePolicy)
        self.control_button_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.control_button_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.control_button_frame.setObjectName("control_button_frame")
        self.Buttons_2 = QtWidgets.QHBoxLayout(self.control_button_frame)
        self.Buttons_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.Buttons_2.setContentsMargins(1, 1, 1, 1)
        self.Buttons_2.setSpacing(1)
        self.Buttons_2.setObjectName("Buttons_2")
        self.mute_btn = QtWidgets.QPushButton(self.control_button_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mute_btn.sizePolicy().hasHeightForWidth())
        self.mute_btn.setSizePolicy(sizePolicy)
        self.mute_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mute_btn.setBaseSize(QtCore.QSize(30, 75))
        self.mute_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/noun_Mute_1939974.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mute_btn.setIcon(icon)
        self.mute_btn.setFlat(False)
        self.mute_btn.setObjectName("mute_btn")
        self.Buttons_2.addWidget(self.mute_btn)
        self.horizontalSlider = QtWidgets.QSlider(self.control_button_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider.sizePolicy().hasHeightForWidth())
        self.horizontalSlider.setSizePolicy(sizePolicy)
        self.horizontalSlider.setMaximumSize(QtCore.QSize(80, 16777215))
        self.horizontalSlider.setPageStep(5)
        self.horizontalSlider.setSliderPosition(0)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setInvertedAppearance(False)
        self.horizontalSlider.setInvertedControls(False)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.Buttons_2.addWidget(self.horizontalSlider)
        self.volume_btn = QtWidgets.QPushButton(self.control_button_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.volume_btn.sizePolicy().hasHeightForWidth())
        self.volume_btn.setSizePolicy(sizePolicy)
        self.volume_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.volume_btn.setBaseSize(QtCore.QSize(30, 75))
        self.volume_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/noun_Sound_1939979.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.volume_btn.setIcon(icon1)
        self.volume_btn.setFlat(False)
        self.volume_btn.setObjectName("volume_btn")
        self.Buttons_2.addWidget(self.volume_btn)
        self.skip_back = QtWidgets.QPushButton(self.control_button_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skip_back.sizePolicy().hasHeightForWidth())
        self.skip_back.setSizePolicy(sizePolicy)
        self.skip_back.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.skip_back.setBaseSize(QtCore.QSize(30, 75))
        self.skip_back.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/noun_rewind_1939969.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.skip_back.setIcon(icon2)
        self.skip_back.setFlat(False)
        self.skip_back.setObjectName("skip_back")
        self.Buttons_2.addWidget(self.skip_back)
        self.skip_track_back = QtWidgets.QPushButton(self.control_button_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skip_track_back.sizePolicy().hasHeightForWidth())
        self.skip_track_back.setSizePolicy(sizePolicy)
        self.skip_track_back.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.skip_track_back.setBaseSize(QtCore.QSize(30, 75))
        self.skip_track_back.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/noun_previous_1939964.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.skip_track_back.setIcon(icon3)
        self.skip_track_back.setFlat(False)
        self.skip_track_back.setObjectName("skip_track_back")
        self.Buttons_2.addWidget(self.skip_track_back)
        self.stop = QtWidgets.QPushButton(self.control_button_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop.sizePolicy().hasHeightForWidth())
        self.stop.setSizePolicy(sizePolicy)
        self.stop.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.stop.setBaseSize(QtCore.QSize(30, 75))
        self.stop.setText("")
        self.stop.setFlat(False)
        self.stop.setObjectName("stop")
        self.Buttons_2.addWidget(self.stop)
        self.play_button = QtWidgets.QPushButton(self.control_button_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.play_button.sizePolicy().hasHeightForWidth())
        self.play_button.setSizePolicy(sizePolicy)
        self.play_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.play_button.setBaseSize(QtCore.QSize(30, 75))
        self.play_button.setText("")
        self.play_button.setDefault(False)
        self.play_button.setFlat(False)
        self.play_button.setObjectName("play_button")
        self.Buttons_2.addWidget(self.play_button)
        self.pause = QtWidgets.QPushButton(self.control_button_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pause.sizePolicy().hasHeightForWidth())
        self.pause.setSizePolicy(sizePolicy)
        self.pause.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pause.setBaseSize(QtCore.QSize(30, 75))
        self.pause.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/noun_pause_1939967.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pause.setIcon(icon4)
        self.pause.setFlat(False)
        self.pause.setObjectName("pause")
        self.Buttons_2.addWidget(self.pause)
        self.skip_track_fwd = QtWidgets.QPushButton(self.control_button_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skip_track_fwd.sizePolicy().hasHeightForWidth())
        self.skip_track_fwd.setSizePolicy(sizePolicy)
        self.skip_track_fwd.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.skip_track_fwd.setBaseSize(QtCore.QSize(30, 75))
        self.skip_track_fwd.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/noun_Next_1939966.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.skip_track_fwd.setIcon(icon5)
        self.skip_track_fwd.setFlat(False)
        self.skip_track_fwd.setObjectName("skip_track_fwd")
        self.Buttons_2.addWidget(self.skip_track_fwd)
        self.skip_ford = QtWidgets.QPushButton(self.control_button_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skip_ford.sizePolicy().hasHeightForWidth())
        self.skip_ford.setSizePolicy(sizePolicy)
        self.skip_ford.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.skip_ford.setBaseSize(QtCore.QSize(30, 75))
        self.skip_ford.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/noun_forward_1939968.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.skip_ford.setIcon(icon6)
        self.skip_ford.setFlat(False)
        self.skip_ford.setObjectName("skip_ford")
        self.Buttons_2.addWidget(self.skip_ford)
        self.shuffle_btn = QtWidgets.QPushButton(self.control_button_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shuffle_btn.sizePolicy().hasHeightForWidth())
        self.shuffle_btn.setSizePolicy(sizePolicy)
        self.shuffle_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.shuffle_btn.setBaseSize(QtCore.QSize(30, 75))
        self.shuffle_btn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/noun_Shuffle_1939972.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shuffle_btn.setIcon(icon7)
        self.shuffle_btn.setFlat(False)
        self.shuffle_btn.setObjectName("shuffle_btn")
        self.Buttons_2.addWidget(self.shuffle_btn)
        self.horizontalFrame = QtWidgets.QFrame(self.control_button_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame.sizePolicy().hasHeightForWidth())
        self.horizontalFrame.setSizePolicy(sizePolicy)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lcdNumber = QtWidgets.QLCDNumber(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber.sizePolicy().hasHeightForWidth())
        self.lcdNumber.setSizePolicy(sizePolicy)
        self.lcdNumber.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumber.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumber.setDigitCount(2)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber.setProperty("value", 59.0)
        self.lcdNumber.setObjectName("lcdNumber")
        self.horizontalLayout.addWidget(self.lcdNumber)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_2.sizePolicy().hasHeightForWidth())
        self.lcdNumber_2.setSizePolicy(sizePolicy)
        self.lcdNumber_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumber_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumber_2.setDigitCount(2)
        self.lcdNumber_2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_2.setProperty("value", 59.0)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.horizontalLayout.addWidget(self.lcdNumber_2)
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_3.sizePolicy().hasHeightForWidth())
        self.lcdNumber_3.setSizePolicy(sizePolicy)
        self.lcdNumber_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumber_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumber_3.setDigitCount(2)
        self.lcdNumber_3.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_3.setProperty("value", 59.0)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.horizontalLayout.addWidget(self.lcdNumber_3)
        self.Buttons_2.addWidget(self.horizontalFrame)
        spacerItem = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Buttons_2.addItem(spacerItem)
        self.lineEdit = QtWidgets.QLineEdit(self.control_button_frame)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit.setBaseSize(QtCore.QSize(0, 22))
        self.lineEdit.setMaxLength(50)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.Buttons_2.addWidget(self.lineEdit)
        self.toolButton = QtWidgets.QToolButton(self.control_button_frame)
        self.toolButton.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.toolButton.setFont(font)
        self.toolButton.setCheckable(False)
        self.toolButton.setAutoRaise(False)
        self.toolButton.setObjectName("toolButton")
        self.Buttons_2.addWidget(self.toolButton)
        self.gridLayout_4.addWidget(self.control_button_frame, 0, 0, 1, 2)
        self.tableView_music = QtWidgets.QTableView(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView_music.sizePolicy().hasHeightForWidth())
        self.tableView_music.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableView_music.setFont(font)
        self.tableView_music.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableView_music.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView_music.setProperty("showDropIndicator", False)
        self.tableView_music.setDragEnabled(False)
        self.tableView_music.setDragDropOverwriteMode(False)
        self.tableView_music.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableView_music.setAlternatingRowColors(True)
        self.tableView_music.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableView_music.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView_music.setShowGrid(False)
        self.tableView_music.setGridStyle(QtCore.Qt.NoPen)
        self.tableView_music.setSortingEnabled(True)
        self.tableView_music.setWordWrap(False)
        self.tableView_music.setCornerButtonEnabled(False)
        self.tableView_music.setObjectName("tableView_music")
        self.tableView_music.verticalHeader().setVisible(False)
        self.tableView_music.verticalHeader().setCascadingSectionResizes(False)
        self.tableView_music.verticalHeader().setDefaultSectionSize(0)
        self.gridLayout_4.addWidget(self.tableView_music, 1, 0, 2, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pixmap_cov = QtWidgets.QLabel(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pixmap_cov.sizePolicy().hasHeightForWidth())
        self.pixmap_cov.setSizePolicy(sizePolicy)
        self.pixmap_cov.setMinimumSize(QtCore.QSize(300, 300))
        self.pixmap_cov.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pixmap_cov.setText("")
        self.pixmap_cov.setAlignment(QtCore.Qt.AlignCenter)
        self.pixmap_cov.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.pixmap_cov.setObjectName("pixmap_cov")
        self.verticalLayout.addWidget(self.pixmap_cov)
        self.file_meta_info_list = QtWidgets.QListView(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_meta_info_list.sizePolicy().hasHeightForWidth())
        self.file_meta_info_list.setSizePolicy(sizePolicy)
        self.file_meta_info_list.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.file_meta_info_list.setObjectName("file_meta_info_list")
        self.verticalLayout.addWidget(self.file_meta_info_list)
        self.gridLayout_4.addLayout(self.verticalLayout, 2, 1, 1, 1)
        self.tracks_list = QtWidgets.QListWidget(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tracks_list.sizePolicy().hasHeightForWidth())
        self.tracks_list.setSizePolicy(sizePolicy)
        self.tracks_list.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tracks_list.setObjectName("tracks_list")
        self.gridLayout_4.addWidget(self.tracks_list, 1, 1, 1, 1)
        self.tracks_list.raise_()
        self.control_button_frame.raise_()
        self.tableView_music.raise_()
        self.gridLayout_3.addWidget(self.gridFrame, 1, 0, 1, 1)
        self.tabWidget.addTab(self.music, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1065, 21))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        self.menuFiles = QtWidgets.QMenu(self.menubar)
        self.menuFiles.setTearOffEnabled(False)
        self.menuFiles.setSeparatorsCollapsible(False)
        self.menuFiles.setObjectName("menuFiles")
        MainWindow.setMenuBar(self.menubar)
        self.actionAdd_Files_to_librayr = QtWidgets.QAction(MainWindow)
        self.actionAdd_Files_to_librayr.setCheckable(False)
        self.actionAdd_Files_to_librayr.setObjectName("actionAdd_Files_to_librayr")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionRescan = QtWidgets.QAction(MainWindow)
        self.actionRescan.setObjectName("actionRescan")
        self.menuFiles.addAction(self.actionAdd_Files_to_librayr)
        self.menuFiles.addAction(self.actionSettings)
        self.menuFiles.addAction(self.actionRescan)
        self.menubar.addAction(self.menuFiles.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setText(_translate("MainWindow", "Search Library"))
        self.toolButton.setText(_translate("MainWindow", "Search"))
        self.toolButton.setShortcut(_translate("MainWindow", "Return"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.music), _translate("MainWindow", "Music"))
        self.menuFiles.setTitle(_translate("MainWindow", "Files"))
        self.actionAdd_Files_to_librayr.setText(_translate("MainWindow", "Add Files to library"))
        self.actionAdd_Files_to_librayr.setShortcut(_translate("MainWindow", "Ins"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionRescan.setText(_translate("MainWindow", "Rescan"))
        self.actionRescan.setShortcut(_translate("MainWindow", "Ctrl+S"))
# import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
