# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\settings.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_setting_main_window(object):
    def setupUi(self, setting_main_window):
        setting_main_window.setObjectName("setting_main_window")
        setting_main_window.resize(700, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(setting_main_window.sizePolicy().hasHeightForWidth())
        setting_main_window.setSizePolicy(sizePolicy)
        setting_main_window.setMinimumSize(QtCore.QSize(700, 600))
        setting_main_window.setMaximumSize(QtCore.QSize(700, 600))
        self.centralwidget = QtWidgets.QWidget(setting_main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_2.setSpacing(1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.player_box = QtWidgets.QGroupBox(self.page)
        self.player_box.setFlat(False)
        self.player_box.setObjectName("player_box")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.player_box)
        self.gridLayout_6.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_3.addWidget(self.player_box, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_7.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_7.setSpacing(1)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox_2)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 487, 551))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setContentsMargins(1, 1, 1, 1)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalFrame_filepath = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.verticalFrame_filepath.setMinimumSize(QtCore.QSize(485, 182))
        self.verticalFrame_filepath.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.verticalFrame_filepath.setObjectName("verticalFrame_filepath")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame_filepath)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.line_11 = QtWidgets.QFrame(self.verticalFrame_filepath)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout.addWidget(self.line_11)
        self.file_path = QtWidgets.QLabel(self.verticalFrame_filepath)
        self.file_path.setMinimumSize(QtCore.QSize(481, 13))
        self.file_path.setObjectName("file_path")
        self.verticalLayout.addWidget(self.file_path)
        self.file_path_list = QtWidgets.QListView(self.verticalFrame_filepath)
        self.file_path_list.setMinimumSize(QtCore.QSize(481, 164))
        self.file_path_list.setObjectName("file_path_list")
        self.verticalLayout.addWidget(self.file_path_list)
        self.gridLayout.addWidget(self.verticalFrame_filepath, 0, 0, 1, 1)
        self.verticalFrame_file_ext = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.verticalFrame_file_ext.setMinimumSize(QtCore.QSize(485, 181))
        self.verticalFrame_file_ext.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.verticalFrame_file_ext.setObjectName("verticalFrame_file_ext")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalFrame_file_ext)
        self.verticalLayout_5.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_5.setSpacing(1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.file_ext = QtWidgets.QLabel(self.verticalFrame_file_ext)
        self.file_ext.setMinimumSize(QtCore.QSize(481, 13))
        self.file_ext.setObjectName("file_ext")
        self.verticalLayout_5.addWidget(self.file_ext)
        self.file_ext_list = QtWidgets.QListView(self.verticalFrame_file_ext)
        self.file_ext_list.setMinimumSize(QtCore.QSize(481, 163))
        self.file_ext_list.setUniformItemSizes(False)
        self.file_ext_list.setObjectName("file_ext_list")
        self.verticalLayout_5.addWidget(self.file_ext_list)
        self.gridLayout.addWidget(self.verticalFrame_file_ext, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_7.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 1, 1, 1)
        self.labe_lbutton_frame = QtWidgets.QFrame(self.centralwidget)
        self.labe_lbutton_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labe_lbutton_frame.setObjectName("labe_lbutton_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.labe_lbutton_frame)
        self.verticalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_player = QtWidgets.QPushButton(self.labe_lbutton_frame)
        self.pushButton_player.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_player.setFlat(True)
        self.pushButton_player.setObjectName("pushButton_player")
        self.verticalLayout_2.addWidget(self.pushButton_player)
        self.line = QtWidgets.QFrame(self.labe_lbutton_frame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.pushButton_library = QtWidgets.QPushButton(self.labe_lbutton_frame)
        self.pushButton_library.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_library.setFlat(True)
        self.pushButton_library.setObjectName("pushButton_library")
        self.verticalLayout_2.addWidget(self.pushButton_library)
        self.line_2 = QtWidgets.QFrame(self.labe_lbutton_frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.pushButton_10 = QtWidgets.QPushButton(self.labe_lbutton_frame)
        self.pushButton_10.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_10.setFlat(True)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_2.addWidget(self.pushButton_10)
        self.line_3 = QtWidgets.QFrame(self.labe_lbutton_frame)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.pushButton_12 = QtWidgets.QPushButton(self.labe_lbutton_frame)
        self.pushButton_12.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_12.setFlat(True)
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_2.addWidget(self.pushButton_12)
        self.line_4 = QtWidgets.QFrame(self.labe_lbutton_frame)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.labe_lbutton_frame)
        self.pushButton_5.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_5.setFlat(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5)
        self.line_5 = QtWidgets.QFrame(self.labe_lbutton_frame)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_2.addWidget(self.line_5)
        self.pushButton_11 = QtWidgets.QPushButton(self.labe_lbutton_frame)
        self.pushButton_11.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_11.setFlat(True)
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_2.addWidget(self.pushButton_11, 0, QtCore.Qt.AlignLeft)
        self.line_6 = QtWidgets.QFrame(self.labe_lbutton_frame)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_2.addWidget(self.line_6)
        self.pushButton_9 = QtWidgets.QPushButton(self.labe_lbutton_frame)
        self.pushButton_9.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_9.setFlat(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_2.addWidget(self.pushButton_9)
        self.line_7 = QtWidgets.QFrame(self.labe_lbutton_frame)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_2.addWidget(self.line_7)
        self.pushButton_7 = QtWidgets.QPushButton(self.labe_lbutton_frame)
        self.pushButton_7.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_7.setFlat(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_2.addWidget(self.pushButton_7)
        self.line_8 = QtWidgets.QFrame(self.labe_lbutton_frame)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_2.addWidget(self.line_8)
        self.pushButton_8 = QtWidgets.QPushButton(self.labe_lbutton_frame)
        self.pushButton_8.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_8.setFlat(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_2.addWidget(self.pushButton_8)
        self.line_9 = QtWidgets.QFrame(self.labe_lbutton_frame)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_2.addWidget(self.line_9)
        self.pushButton_6 = QtWidgets.QPushButton(self.labe_lbutton_frame)
        self.pushButton_6.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_6.setFlat(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_2.addWidget(self.pushButton_6)
        self.line_10 = QtWidgets.QFrame(self.labe_lbutton_frame)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_2.addWidget(self.line_10)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout_2.addWidget(self.labe_lbutton_frame, 0, 0, 1, 1)
        self.botm_btn_frame = QtWidgets.QFrame(self.centralwidget)
        self.botm_btn_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.botm_btn_frame.setObjectName("botm_btn_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.botm_btn_frame)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.ok_btn = QtWidgets.QPushButton(self.botm_btn_frame)
        self.ok_btn.setObjectName("ok_btn")
        self.horizontalLayout.addWidget(self.ok_btn)
        self.apply_btn = QtWidgets.QPushButton(self.botm_btn_frame)
        self.apply_btn.setObjectName("apply_btn")
        self.horizontalLayout.addWidget(self.apply_btn)
        self.cancel_btn = QtWidgets.QPushButton(self.botm_btn_frame)
        self.cancel_btn.setFlat(False)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout.addWidget(self.cancel_btn)
        self.gridLayout_2.addWidget(self.botm_btn_frame, 1, 0, 1, 2)
        setting_main_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(setting_main_window)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(setting_main_window)

    def retranslateUi(self, setting_main_window):
        _translate = QtCore.QCoreApplication.translate
        setting_main_window.setWindowTitle(_translate("setting_main_window", "Settings"))
        self.player_box.setTitle(_translate("setting_main_window", "Player"))
        self.groupBox_2.setTitle(_translate("setting_main_window", "Library"))
        self.file_path.setText(_translate("setting_main_window", "File Path"))
        self.file_ext.setText(_translate("setting_main_window", "File Extensions"))
        self.pushButton_player.setText(_translate("setting_main_window", "Player"))
        self.pushButton_library.setText(_translate("setting_main_window", "Library"))
        self.pushButton_10.setText(_translate("setting_main_window", "Player"))
        self.pushButton_12.setText(_translate("setting_main_window", "Player"))
        self.pushButton_5.setText(_translate("setting_main_window", "Player"))
        self.pushButton_11.setText(_translate("setting_main_window", "Player"))
        self.pushButton_9.setText(_translate("setting_main_window", "Player"))
        self.pushButton_7.setText(_translate("setting_main_window", "Player"))
        self.pushButton_8.setText(_translate("setting_main_window", "Player"))
        self.pushButton_6.setText(_translate("setting_main_window", "Player"))
        self.ok_btn.setText(_translate("setting_main_window", "Ok"))
        self.apply_btn.setText(_translate("setting_main_window", "Apply"))
        self.cancel_btn.setText(_translate("setting_main_window", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    setting_main_window = QtWidgets.QMainWindow()
    ui = Ui_setting_main_window()
    ui.setupUi(setting_main_window)
    setting_main_window.show()
    sys.exit(app.exec_())
