# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tagger_ui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 584)
        MainWindow.setMinimumSize(QtCore.QSize(720, 584))
        MainWindow.setMaximumSize(QtCore.QSize(720, 584))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(720, 540))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(4, 4, 4, 4)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(712, 550))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setObjectName("tabWidget")
        self.property_tab = QtWidgets.QWidget()
        self.property_tab.setObjectName("property_tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.property_tab)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridFrame = QtWidgets.QFrame(self.property_tab)
        self.gridFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.gridFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.gridFrame.setObjectName("gridFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridFrame)
        self.gridLayout_2.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 3, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem1, 0, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.gridFrame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setVerticalSpacing(8)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_23 = QtWidgets.QLabel(self.frame_3)
        self.label_23.setMinimumSize(QtCore.QSize(128, 0))
        self.label_23.setObjectName("label_23")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.lineEdit_art = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_art.setObjectName("lineEdit_art")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_art)
        self.label_24 = QtWidgets.QLabel(self.frame_3)
        self.label_24.setMinimumSize(QtCore.QSize(128, 0))
        self.label_24.setObjectName("label_24")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.lineEdit_tit = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_tit.setObjectName("lineEdit_tit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_tit)
        self.lineEdit_alb_a = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_alb_a.setObjectName("lineEdit_alb_a")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_alb_a)
        self.label_25 = QtWidgets.QLabel(self.frame_3)
        self.label_25.setMinimumSize(QtCore.QSize(128, 0))
        self.label_25.setObjectName("label_25")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.lineEdit_alb = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_alb.setObjectName("lineEdit_alb")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_alb)
        self.label_26 = QtWidgets.QLabel(self.frame_3)
        self.label_26.setMinimumSize(QtCore.QSize(128, 0))
        self.label_26.setObjectName("label_26")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.lineEdit_gen = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_gen.setObjectName("lineEdit_gen")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_gen)
        self.label_27 = QtWidgets.QLabel(self.frame_3)
        self.label_27.setMinimumSize(QtCore.QSize(128, 0))
        self.label_27.setObjectName("label_27")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.lineEdit_comp = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_comp.setObjectName("lineEdit_comp")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_comp)
        self.label_28 = QtWidgets.QLabel(self.frame_3)
        self.label_28.setMinimumSize(QtCore.QSize(128, 0))
        self.label_28.setObjectName("label_28")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.lineEdit_dur = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_dur.setObjectName("lineEdit_dur")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_dur)
        self.label_29 = QtWidgets.QLabel(self.frame_3)
        self.label_29.setMinimumSize(QtCore.QSize(128, 0))
        self.label_29.setObjectName("label_29")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.lineEdit_off = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_off.setObjectName("lineEdit_off")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit_off)
        self.label_30 = QtWidgets.QLabel(self.frame_3)
        self.label_30.setMinimumSize(QtCore.QSize(128, 0))
        self.label_30.setObjectName("label_30")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.lineEdit_bitr = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_bitr.setObjectName("lineEdit_bitr")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit_bitr)
        self.label_31 = QtWidgets.QLabel(self.frame_3)
        self.label_31.setMinimumSize(QtCore.QSize(128, 0))
        self.label_31.setObjectName("label_31")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.lineEdit_chnl = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_chnl.setObjectName("lineEdit_chnl")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lineEdit_chnl)
        self.label_32 = QtWidgets.QLabel(self.frame_3)
        self.label_32.setMinimumSize(QtCore.QSize(128, 0))
        self.label_32.setObjectName("label_32")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.horizontalLayout.addLayout(self.formLayout_3)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setVerticalSpacing(8)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_33 = QtWidgets.QLabel(self.frame_3)
        self.label_33.setMinimumSize(QtCore.QSize(128, 0))
        self.label_33.setObjectName("label_33")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.lineEdit_fs = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_fs.setObjectName("lineEdit_fs")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_fs)
        self.label_34 = QtWidgets.QLabel(self.frame_3)
        self.label_34.setMinimumSize(QtCore.QSize(128, 0))
        self.label_34.setObjectName("label_34")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.lineEdit_sr = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_sr.setObjectName("lineEdit_sr")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_sr)
        self.label_35 = QtWidgets.QLabel(self.frame_3)
        self.label_35.setMinimumSize(QtCore.QSize(128, 0))
        self.label_35.setObjectName("label_35")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.lineEdit_dis = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_dis.setObjectName("lineEdit_dis")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_dis)
        self.label_36 = QtWidgets.QLabel(self.frame_3)
        self.label_36.setMinimumSize(QtCore.QSize(128, 0))
        self.label_36.setObjectName("label_36")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_36)
        self.lineEdit_dist = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_dist.setObjectName("lineEdit_dist")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_dist)
        self.label_37 = QtWidgets.QLabel(self.frame_3)
        self.label_37.setMinimumSize(QtCore.QSize(128, 0))
        self.label_37.setObjectName("label_37")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_37)
        self.lineEdit_tra = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_tra.setObjectName("lineEdit_tra")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_tra)
        self.label_38 = QtWidgets.QLabel(self.frame_3)
        self.label_38.setMinimumSize(QtCore.QSize(128, 0))
        self.label_38.setObjectName("label_38")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_38)
        self.lineEdit_traT = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_traT.setObjectName("lineEdit_traT")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_traT)
        self.label_39 = QtWidgets.QLabel(self.frame_3)
        self.label_39.setMinimumSize(QtCore.QSize(128, 0))
        self.label_39.setObjectName("label_39")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_39)
        self.lineEdit_yr = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_yr.setObjectName("lineEdit_yr")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_yr)
        self.label_40 = QtWidgets.QLabel(self.frame_3)
        self.label_40.setMinimumSize(QtCore.QSize(128, 0))
        self.label_40.setObjectName("label_40")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_40)
        self.lineEdit_rat = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_rat.setObjectName("lineEdit_rat")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit_rat)
        self.label_41 = QtWidgets.QLabel(self.frame_3)
        self.label_41.setMinimumSize(QtCore.QSize(128, 0))
        self.label_41.setObjectName("label_41")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_41)
        self.lineEdit_dadd = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_dadd.setObjectName("lineEdit_dadd")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit_dadd)
        self.label_42 = QtWidgets.QLabel(self.frame_3)
        self.label_42.setMinimumSize(QtCore.QSize(128, 0))
        self.label_42.setObjectName("label_42")
        self.formLayout_4.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_42)
        self.lineEdit_pcnt = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_pcnt.setObjectName("lineEdit_pcnt")
        self.formLayout_4.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lineEdit_pcnt)
        self.horizontalLayout.addLayout(self.formLayout_4)
        self.gridLayout_2.addWidget(self.frame_3, 2, 0, 1, 2)
        self.line = QtWidgets.QFrame(self.gridFrame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 4, 0, 1, 2)
        self.frame = QtWidgets.QFrame(self.gridFrame)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 240))
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_4.setSpacing(2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_22 = QtWidgets.QLabel(self.frame)
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 1, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.frame)
        self.label_21.setEnabled(True)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 3, 0, 1, 1)
        self.lineEdit_file_name = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_file_name.setObjectName("lineEdit_file_name")
        self.gridLayout_4.addWidget(self.lineEdit_file_name, 2, 0, 1, 1)
        self.lineEdit_file_path = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_file_path.setEnabled(True)
        self.lineEdit_file_path.setReadOnly(True)
        self.lineEdit_file_path.setObjectName("lineEdit_file_path")
        self.gridLayout_4.addWidget(self.lineEdit_file_path, 4, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 5, 0, 1, 2)
        self.label_43 = QtWidgets.QLabel(self.gridFrame)
        self.label_43.setObjectName("label_43")
        self.gridLayout_2.addWidget(self.label_43, 0, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.gridFrame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 1, 0, 1, 2)
        self.gridLayout_5.addWidget(self.gridFrame, 0, 0, 1, 1)
        self.tabWidget.addTab(self.property_tab, "")
        self.tags_tab = QtWidgets.QWidget()
        self.tags_tab.setObjectName("tags_tab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tags_tab)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame_4 = QtWidgets.QFrame(self.tags_tab)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_6.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_44 = QtWidgets.QLabel(self.frame_4)
        self.label_44.setMinimumSize(QtCore.QSize(128, 0))
        self.label_44.setObjectName("label_44")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_44)
        self.lineEdit_art_2 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_art_2.setObjectName("lineEdit_art_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_art_2)
        self.label_45 = QtWidgets.QLabel(self.frame_4)
        self.label_45.setMinimumSize(QtCore.QSize(128, 0))
        self.label_45.setObjectName("label_45")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_45)
        self.lineEdit_tit_2 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_tit_2.setObjectName("lineEdit_tit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_tit_2)
        self.label_46 = QtWidgets.QLabel(self.frame_4)
        self.label_46.setMinimumSize(QtCore.QSize(128, 0))
        self.label_46.setObjectName("label_46")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_46)
        self.lineEdit_alb_a_2 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_alb_a_2.setObjectName("lineEdit_alb_a_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_alb_a_2)
        self.label_47 = QtWidgets.QLabel(self.frame_4)
        self.label_47.setMinimumSize(QtCore.QSize(128, 0))
        self.label_47.setObjectName("label_47")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_47)
        self.lineEdit_alb_2 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_alb_2.setObjectName("lineEdit_alb_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_alb_2)
        self.label_48 = QtWidgets.QLabel(self.frame_4)
        self.label_48.setMinimumSize(QtCore.QSize(128, 0))
        self.label_48.setObjectName("label_48")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_48)
        self.lineEdit_gen_2 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_gen_2.setObjectName("lineEdit_gen_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_gen_2)
        self.label_49 = QtWidgets.QLabel(self.frame_4)
        self.label_49.setMinimumSize(QtCore.QSize(128, 0))
        self.label_49.setObjectName("label_49")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_49)
        self.lineEdit_comp_2 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_comp_2.setObjectName("lineEdit_comp_2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_comp_2)
        self.label_50 = QtWidgets.QLabel(self.frame_4)
        self.label_50.setMinimumSize(QtCore.QSize(128, 0))
        self.label_50.setObjectName("label_50")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_50)
        self.lineEdit_dur_2 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_dur_2.setObjectName("lineEdit_dur_2")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_dur_2)
        self.label_51 = QtWidgets.QLabel(self.frame_4)
        self.label_51.setMinimumSize(QtCore.QSize(128, 0))
        self.label_51.setObjectName("label_51")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_51)
        self.lineEdit_off_2 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_off_2.setObjectName("lineEdit_off_2")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit_off_2)
        self.label_52 = QtWidgets.QLabel(self.frame_4)
        self.label_52.setMinimumSize(QtCore.QSize(128, 0))
        self.label_52.setObjectName("label_52")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_52)
        self.lineEdit_bitr_2 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_bitr_2.setObjectName("lineEdit_bitr_2")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit_bitr_2)
        self.label_53 = QtWidgets.QLabel(self.frame_4)
        self.label_53.setMinimumSize(QtCore.QSize(128, 0))
        self.label_53.setObjectName("label_53")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_53)
        self.lineEdit_chnl_2 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_chnl_2.setObjectName("lineEdit_chnl_2")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lineEdit_chnl_2)
        self.label_54 = QtWidgets.QLabel(self.frame_4)
        self.label_54.setMinimumSize(QtCore.QSize(128, 0))
        self.label_54.setObjectName("label_54")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_54)
        self.lineEdit_fs_2 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_fs_2.setObjectName("lineEdit_fs_2")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.lineEdit_fs_2)
        self.label_55 = QtWidgets.QLabel(self.frame_4)
        self.label_55.setMinimumSize(QtCore.QSize(128, 0))
        self.label_55.setObjectName("label_55")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_55)
        self.lineEdit_sr_2 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_sr_2.setObjectName("lineEdit_sr_2")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.lineEdit_sr_2)
        self.label_56 = QtWidgets.QLabel(self.frame_4)
        self.label_56.setMinimumSize(QtCore.QSize(128, 0))
        self.label_56.setObjectName("label_56")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_56)
        self.lineEdit_dis_2 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_dis_2.setObjectName("lineEdit_dis_2")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.lineEdit_dis_2)
        self.label_57 = QtWidgets.QLabel(self.frame_4)
        self.label_57.setMinimumSize(QtCore.QSize(128, 0))
        self.label_57.setObjectName("label_57")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_57)
        self.lineEdit_dist_2 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_dist_2.setObjectName("lineEdit_dist_2")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.lineEdit_dist_2)
        self.label_58 = QtWidgets.QLabel(self.frame_4)
        self.label_58.setMinimumSize(QtCore.QSize(128, 0))
        self.label_58.setObjectName("label_58")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_58)
        self.lineEdit_tra_2 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_tra_2.setObjectName("lineEdit_tra_2")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.lineEdit_tra_2)
        self.label_59 = QtWidgets.QLabel(self.frame_4)
        self.label_59.setMinimumSize(QtCore.QSize(128, 0))
        self.label_59.setObjectName("label_59")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.label_59)
        self.lineEdit_traT_2 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_traT_2.setObjectName("lineEdit_traT_2")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.lineEdit_traT_2)
        self.label_60 = QtWidgets.QLabel(self.frame_4)
        self.label_60.setMinimumSize(QtCore.QSize(128, 0))
        self.label_60.setObjectName("label_60")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.label_60)
        self.lineEdit_yr_2 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_yr_2.setObjectName("lineEdit_yr_2")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.lineEdit_yr_2)
        self.gridLayout_6.addLayout(self.formLayout, 0, 0, 6, 1)
        self.comboBox_cover = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_cover.setObjectName("comboBox_cover")
        self.gridLayout_6.addWidget(self.comboBox_cover, 0, 1, 1, 5)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_6.addWidget(self.pushButton_4, 5, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_6.addWidget(self.pushButton_2, 5, 3, 1, 1)
        self.pushButton_Findcov = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_Findcov.setObjectName("pushButton_Findcov")
        self.gridLayout_6.addWidget(self.pushButton_Findcov, 0, 6, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_6.addWidget(self.textBrowser, 4, 1, 1, 6)
        self.lineEdit_63_web = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_63_web.setObjectName("lineEdit_63_web")
        self.gridLayout_6.addWidget(self.lineEdit_63_web, 5, 4, 1, 3)
        self.Cover_image_pix = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Cover_image_pix.sizePolicy().hasHeightForWidth())
        self.Cover_image_pix.setSizePolicy(sizePolicy)
        self.Cover_image_pix.setMinimumSize(QtCore.QSize(300, 250))
        self.Cover_image_pix.setMaximumSize(QtCore.QSize(16777215, 250))
        self.Cover_image_pix.setFrameShape(QtWidgets.QFrame.Box)
        self.Cover_image_pix.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Cover_image_pix.setText("")
        self.Cover_image_pix.setScaledContents(True)
        self.Cover_image_pix.setObjectName("Cover_image_pix")
        self.gridLayout_6.addWidget(self.Cover_image_pix, 2, 1, 1, 6)
        self.gridLayout_7.addWidget(self.frame_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tags_tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_66 = QtWidgets.QLabel(self.tab_3)
        self.label_66.setObjectName("label_66")
        self.horizontalLayout_2.addWidget(self.label_66)
        self.radioButton = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_2.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_2.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.tab_3)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_2.addWidget(self.radioButton_3)
        self.gridLayout_8.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.tableView = QtWidgets.QTableView(self.tab_3)
        self.tableView.setObjectName("tableView")
        self.gridLayout_8.addWidget(self.tableView, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_3.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_3.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_3.addWidget(self.pushButton_7)
        self.gridLayout_8.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.pushButton_save = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout_4.addWidget(self.pushButton_save)
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_4.addWidget(self.pushButton_9)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.label_23.setBuddy(self.lineEdit_art)
        self.label_44.setBuddy(self.lineEdit_art)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_23.setText(_translate("MainWindow", "Artist"))
        self.label_24.setText(_translate("MainWindow", "Title"))
        self.label_25.setText(_translate("MainWindow", "Album"))
        self.label_26.setText(_translate("MainWindow", "Genre"))
        self.label_27.setText(_translate("MainWindow", "Composer"))
        self.label_28.setText(_translate("MainWindow", "Duration"))
        self.label_29.setText(_translate("MainWindow", "Offset"))
        self.label_30.setText(_translate("MainWindow", "Bitrate"))
        self.label_31.setText(_translate("MainWindow", "Channel"))
        self.label_32.setText(_translate("MainWindow", "Album Artist"))
        self.label_33.setText(_translate("MainWindow", "File Size"))
        self.label_34.setText(_translate("MainWindow", "Samplerate"))
        self.label_35.setText(_translate("MainWindow", "Disc"))
        self.label_36.setText(_translate("MainWindow", "Disc Total"))
        self.label_37.setText(_translate("MainWindow", "Track"))
        self.label_38.setText(_translate("MainWindow", "Track Total"))
        self.label_39.setText(_translate("MainWindow", "Year"))
        self.label_40.setText(_translate("MainWindow", "Rating"))
        self.label_41.setText(_translate("MainWindow", "Date Added"))
        self.label_42.setText(_translate("MainWindow", "Play Count"))
        self.label_22.setText(_translate("MainWindow", "Filename"))
        self.label_21.setText(_translate("MainWindow", "File Path"))
        self.label_43.setText(_translate("MainWindow", "Properties"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.property_tab), _translate("MainWindow", "Properties"))
        self.label_44.setText(_translate("MainWindow", "Artist"))
        self.label_45.setText(_translate("MainWindow", "Title"))
        self.label_46.setText(_translate("MainWindow", "Album Artist"))
        self.label_47.setText(_translate("MainWindow", "Album"))
        self.label_48.setText(_translate("MainWindow", "Genre"))
        self.label_49.setText(_translate("MainWindow", "Composer"))
        self.label_50.setText(_translate("MainWindow", "Duration"))
        self.label_51.setText(_translate("MainWindow", "Offset"))
        self.label_52.setText(_translate("MainWindow", "Bitrate"))
        self.label_53.setText(_translate("MainWindow", "Channel"))
        self.label_54.setText(_translate("MainWindow", "File Size"))
        self.label_55.setText(_translate("MainWindow", "Samplerate"))
        self.label_56.setText(_translate("MainWindow", "Disc"))
        self.label_57.setText(_translate("MainWindow", "Disc Total"))
        self.label_58.setText(_translate("MainWindow", "Track"))
        self.label_59.setText(_translate("MainWindow", "Track Total"))
        self.label_60.setText(_translate("MainWindow", "Year"))
        self.pushButton_4.setText(_translate("MainWindow", "Delete Lyrics"))
        self.pushButton_2.setText(_translate("MainWindow", "Find Lyrics"))
        self.pushButton_Findcov.setText(_translate("MainWindow", "Find Cover"))
        self.lineEdit_63_web.setText(_translate("MainWindow", "Enter Website"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tags_tab), _translate("MainWindow", "Tags"))
        self.label_66.setText(_translate("MainWindow", "TextLabel"))
        self.radioButton.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_2.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_3.setText(_translate("MainWindow", "RadioButton"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_5.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_6.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_7.setText(_translate("MainWindow", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Page"))
        self.pushButton_save.setText(_translate("MainWindow", "Save"))
        self.pushButton_9.setText(_translate("MainWindow", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
