[QT_TESTING]
LOAD_DOTENV = true
RECOMPILE_THEME = true
LOADED_THEME = "material_dark"
NOX_EXECUTION_VERBOSITY_DISABLED = true
BENCHMARK_FORMATS = false
SUPPORTED_FORMATS = [ "aac", "aiff", "flac", "m4a", "mp3", "ogg", "opus", "wav",]
ENABLED_FORMATS = [ "mp3",]
SOX_PATH = "D:\\Programs\\ffmpeg\\bin\\sox.exe"
TEMP_DIR = "D:\\Dev\\Apollo\\tests\\tempdir"
ASSETS_DIR = "D:\\Dev\\Apollo\\tests\\assets"
DB_PATH = "D:\\Dev\\Apollo\\tests\\tempdir\\testing.db"

[TESTING]
SOX_PATH = "D:\\Programs\\ffmpeg\\bin\\sox.exe"

[QT_TESTING.SERVER]
format = "s16"
chnl = 2
rate = 44100

[QT_TESTING.APOLLO.PLAYBACK_BAR]
LOADED_TRACK = "@none "
VOLUME_LEVEL = 50
STATE_REPEAT = "NONE"
STATE_SHUFFLE = "NONE"
STATE_PLAY = "PAUSE"
