# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\dsp_player.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dsp_player_mainwindow(object):
    def setupUi(self, Dsp_player_mainwindow):
        Dsp_player_mainwindow.setObjectName("Dsp_player_mainwindow")
        Dsp_player_mainwindow.setWindowModality(QtCore.Qt.ApplicationModal)
        Dsp_player_mainwindow.resize(895, 729)
        Dsp_player_mainwindow.setMinimumSize(QtCore.QSize(895, 729))
        Dsp_player_mainwindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(Dsp_player_mainwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.outer_frame_grid = QtWidgets.QFrame(self.centralwidget)
        self.outer_frame_grid.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.outer_frame_grid.setObjectName("outer_frame_grid")
        self.gridLayout = QtWidgets.QGridLayout(self.outer_frame_grid)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.outer_frame_grid)
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.outer_frame_grid)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_5.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_5.setSpacing(4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalFrame = QtWidgets.QFrame(self.tab)
        self.horizontalFrame.setMaximumSize(QtCore.QSize(16777215, 204))
        self.horizontalFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.comboBox = QtWidgets.QComboBox(self.horizontalFrame)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_11.addWidget(self.comboBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_11.addItem(spacerItem1)
        self.EnableB = QtWidgets.QToolButton(self.horizontalFrame)
        self.EnableB.setObjectName("EnableB")
        self.verticalLayout_11.addWidget(self.EnableB)
        self.DisableB = QtWidgets.QToolButton(self.horizontalFrame)
        self.DisableB.setObjectName("DisableB")
        self.verticalLayout_11.addWidget(self.DisableB)
        self.horizontalLayout_2.addLayout(self.verticalLayout_11)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_9 = QtWidgets.QLabel(self.horizontalFrame)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.hp_2 = QtWidgets.QToolButton(self.horizontalFrame)
        self.hp_2.setMinimumSize(QtCore.QSize(25, 25))
        self.hp_2.setIconSize(QtCore.QSize(25, 25))
        self.hp_2.setCheckable(True)
        self.hp_2.setAutoExclusive(True)
        self.hp_2.setObjectName("hp_2")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(Dsp_player_mainwindow)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.hp_2)
        self.horizontalLayout_3.addWidget(self.hp_2)
        self.hp_3 = QtWidgets.QToolButton(self.horizontalFrame)
        self.hp_3.setMinimumSize(QtCore.QSize(25, 25))
        self.hp_3.setCheckable(True)
        self.hp_3.setAutoExclusive(True)
        self.hp_3.setObjectName("hp_3")
        self.buttonGroup_3 = QtWidgets.QButtonGroup(Dsp_player_mainwindow)
        self.buttonGroup_3.setObjectName("buttonGroup_3")
        self.buttonGroup_3.addButton(self.hp_3)
        self.horizontalLayout_3.addWidget(self.hp_3)
        self.hp_4 = QtWidgets.QToolButton(self.horizontalFrame)
        self.hp_4.setMinimumSize(QtCore.QSize(25, 25))
        self.hp_4.setIconSize(QtCore.QSize(25, 25))
        self.hp_4.setCheckable(True)
        self.hp_4.setAutoExclusive(True)
        self.hp_4.setObjectName("hp_4")
        self.buttonGroup_4 = QtWidgets.QButtonGroup(Dsp_player_mainwindow)
        self.buttonGroup_4.setObjectName("buttonGroup_4")
        self.buttonGroup_4.addButton(self.hp_4)
        self.horizontalLayout_3.addWidget(self.hp_4)
        self.hp_5 = QtWidgets.QToolButton(self.horizontalFrame)
        self.hp_5.setMinimumSize(QtCore.QSize(25, 25))
        self.hp_5.setIconSize(QtCore.QSize(25, 25))
        self.hp_5.setCheckable(True)
        self.hp_5.setAutoExclusive(True)
        self.hp_5.setObjectName("hp_5")
        self.buttonGroup_5 = QtWidgets.QButtonGroup(Dsp_player_mainwindow)
        self.buttonGroup_5.setObjectName("buttonGroup_5")
        self.buttonGroup_5.addButton(self.hp_5)
        self.horizontalLayout_3.addWidget(self.hp_5)
        self.hp_6 = QtWidgets.QToolButton(self.horizontalFrame)
        self.hp_6.setMinimumSize(QtCore.QSize(25, 25))
        self.hp_6.setIconSize(QtCore.QSize(25, 25))
        self.hp_6.setCheckable(True)
        self.hp_6.setAutoExclusive(True)
        self.hp_6.setObjectName("hp_6")
        self.buttonGroup_6 = QtWidgets.QButtonGroup(Dsp_player_mainwindow)
        self.buttonGroup_6.setObjectName("buttonGroup_6")
        self.buttonGroup_6.addButton(self.hp_6)
        self.horizontalLayout_3.addWidget(self.hp_6)
        self.hp_7 = QtWidgets.QToolButton(self.horizontalFrame)
        self.hp_7.setMinimumSize(QtCore.QSize(25, 25))
        self.hp_7.setIconSize(QtCore.QSize(25, 25))
        self.hp_7.setCheckable(True)
        self.hp_7.setAutoExclusive(True)
        self.hp_7.setObjectName("hp_7")
        self.buttonGroup_7 = QtWidgets.QButtonGroup(Dsp_player_mainwindow)
        self.buttonGroup_7.setObjectName("buttonGroup_7")
        self.buttonGroup_7.addButton(self.hp_7)
        self.horizontalLayout_3.addWidget(self.hp_7)
        self.hp_8 = QtWidgets.QToolButton(self.horizontalFrame)
        self.hp_8.setMinimumSize(QtCore.QSize(25, 25))
        self.hp_8.setIconSize(QtCore.QSize(25, 25))
        self.hp_8.setCheckable(True)
        self.hp_8.setAutoExclusive(True)
        self.hp_8.setObjectName("hp_8")
        self.buttonGroup_8 = QtWidgets.QButtonGroup(Dsp_player_mainwindow)
        self.buttonGroup_8.setObjectName("buttonGroup_8")
        self.buttonGroup_8.addButton(self.hp_8)
        self.horizontalLayout_3.addWidget(self.hp_8)
        self.verticalLayout_10.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.horizontalFrame)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.lp_2 = QtWidgets.QToolButton(self.horizontalFrame)
        self.lp_2.setMinimumSize(QtCore.QSize(25, 25))
        self.lp_2.setIconSize(QtCore.QSize(25, 25))
        self.lp_2.setCheckable(True)
        self.lp_2.setAutoExclusive(True)
        self.lp_2.setObjectName("lp_2")
        self.buttonGroup_2.addButton(self.lp_2)
        self.horizontalLayout_4.addWidget(self.lp_2)
        self.lp_3 = QtWidgets.QToolButton(self.horizontalFrame)
        self.lp_3.setMinimumSize(QtCore.QSize(25, 25))
        self.lp_3.setIconSize(QtCore.QSize(25, 25))
        self.lp_3.setCheckable(True)
        self.lp_3.setAutoExclusive(True)
        self.lp_3.setObjectName("lp_3")
        self.buttonGroup_3.addButton(self.lp_3)
        self.horizontalLayout_4.addWidget(self.lp_3)
        self.lp_5 = QtWidgets.QToolButton(self.horizontalFrame)
        self.lp_5.setMinimumSize(QtCore.QSize(25, 25))
        self.lp_5.setIconSize(QtCore.QSize(25, 25))
        self.lp_5.setCheckable(True)
        self.lp_5.setAutoExclusive(True)
        self.lp_5.setObjectName("lp_5")
        self.buttonGroup_4.addButton(self.lp_5)
        self.horizontalLayout_4.addWidget(self.lp_5)
        self.lp_4 = QtWidgets.QToolButton(self.horizontalFrame)
        self.lp_4.setMinimumSize(QtCore.QSize(25, 25))
        self.lp_4.setIconSize(QtCore.QSize(25, 25))
        self.lp_4.setCheckable(True)
        self.lp_4.setAutoExclusive(True)
        self.lp_4.setObjectName("lp_4")
        self.buttonGroup_5.addButton(self.lp_4)
        self.horizontalLayout_4.addWidget(self.lp_4)
        self.lp_6 = QtWidgets.QToolButton(self.horizontalFrame)
        self.lp_6.setMinimumSize(QtCore.QSize(25, 25))
        self.lp_6.setIconSize(QtCore.QSize(25, 25))
        self.lp_6.setCheckable(True)
        self.lp_6.setAutoExclusive(True)
        self.lp_6.setObjectName("lp_6")
        self.buttonGroup_6.addButton(self.lp_6)
        self.horizontalLayout_4.addWidget(self.lp_6)
        self.lp_7 = QtWidgets.QToolButton(self.horizontalFrame)
        self.lp_7.setMinimumSize(QtCore.QSize(25, 25))
        self.lp_7.setIconSize(QtCore.QSize(25, 25))
        self.lp_7.setCheckable(True)
        self.lp_7.setAutoExclusive(True)
        self.lp_7.setObjectName("lp_7")
        self.buttonGroup_7.addButton(self.lp_7)
        self.horizontalLayout_4.addWidget(self.lp_7)
        self.lp_8 = QtWidgets.QToolButton(self.horizontalFrame)
        self.lp_8.setMinimumSize(QtCore.QSize(25, 25))
        self.lp_8.setIconSize(QtCore.QSize(25, 25))
        self.lp_8.setCheckable(True)
        self.lp_8.setAutoExclusive(True)
        self.lp_8.setObjectName("lp_8")
        self.buttonGroup_8.addButton(self.lp_8)
        self.horizontalLayout_4.addWidget(self.lp_8)
        self.verticalLayout_10.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.horizontalFrame)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.pn_2 = QtWidgets.QToolButton(self.horizontalFrame)
        self.pn_2.setMinimumSize(QtCore.QSize(25, 25))
        self.pn_2.setIconSize(QtCore.QSize(25, 25))
        self.pn_2.setCheckable(True)
        self.pn_2.setChecked(True)
        self.pn_2.setAutoExclusive(True)
        self.pn_2.setObjectName("pn_2")
        self.buttonGroup_2.addButton(self.pn_2)
        self.horizontalLayout_5.addWidget(self.pn_2)
        self.pn_3 = QtWidgets.QToolButton(self.horizontalFrame)
        self.pn_3.setMinimumSize(QtCore.QSize(25, 25))
        self.pn_3.setIconSize(QtCore.QSize(25, 25))
        self.pn_3.setCheckable(True)
        self.pn_3.setChecked(True)
        self.pn_3.setAutoExclusive(True)
        self.pn_3.setObjectName("pn_3")
        self.buttonGroup_3.addButton(self.pn_3)
        self.horizontalLayout_5.addWidget(self.pn_3)
        self.pn_4 = QtWidgets.QToolButton(self.horizontalFrame)
        self.pn_4.setMinimumSize(QtCore.QSize(25, 25))
        self.pn_4.setIconSize(QtCore.QSize(25, 25))
        self.pn_4.setCheckable(True)
        self.pn_4.setChecked(True)
        self.pn_4.setAutoExclusive(True)
        self.pn_4.setObjectName("pn_4")
        self.buttonGroup_4.addButton(self.pn_4)
        self.horizontalLayout_5.addWidget(self.pn_4)
        self.pn_5 = QtWidgets.QToolButton(self.horizontalFrame)
        self.pn_5.setMinimumSize(QtCore.QSize(25, 25))
        self.pn_5.setIconSize(QtCore.QSize(25, 25))
        self.pn_5.setCheckable(True)
        self.pn_5.setChecked(True)
        self.pn_5.setAutoExclusive(True)
        self.pn_5.setObjectName("pn_5")
        self.buttonGroup_5.addButton(self.pn_5)
        self.horizontalLayout_5.addWidget(self.pn_5)
        self.pn_6 = QtWidgets.QToolButton(self.horizontalFrame)
        self.pn_6.setMinimumSize(QtCore.QSize(25, 25))
        self.pn_6.setIconSize(QtCore.QSize(25, 25))
        self.pn_6.setCheckable(True)
        self.pn_6.setChecked(True)
        self.pn_6.setAutoExclusive(True)
        self.pn_6.setObjectName("pn_6")
        self.buttonGroup_6.addButton(self.pn_6)
        self.horizontalLayout_5.addWidget(self.pn_6)
        self.pn_7 = QtWidgets.QToolButton(self.horizontalFrame)
        self.pn_7.setMinimumSize(QtCore.QSize(25, 25))
        self.pn_7.setIconSize(QtCore.QSize(25, 25))
        self.pn_7.setCheckable(True)
        self.pn_7.setChecked(True)
        self.pn_7.setAutoExclusive(True)
        self.pn_7.setObjectName("pn_7")
        self.buttonGroup_7.addButton(self.pn_7)
        self.horizontalLayout_5.addWidget(self.pn_7)
        self.pn_8 = QtWidgets.QToolButton(self.horizontalFrame)
        self.pn_8.setMinimumSize(QtCore.QSize(25, 25))
        self.pn_8.setIconSize(QtCore.QSize(25, 25))
        self.pn_8.setCheckable(True)
        self.pn_8.setChecked(True)
        self.pn_8.setAutoExclusive(True)
        self.pn_8.setObjectName("pn_8")
        self.buttonGroup_8.addButton(self.pn_8)
        self.horizontalLayout_5.addWidget(self.pn_8)
        self.verticalLayout_10.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_10)
        self.verticalFrame_8 = QtWidgets.QFrame(self.horizontalFrame)
        self.verticalFrame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verticalFrame_8.setObjectName("verticalFrame_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalFrame_8)
        self.verticalLayout_8.setContentsMargins(1, 0, 1, 0)
        self.verticalLayout_8.setSpacing(10)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem3 = QtWidgets.QSpacerItem(20, 39, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem3)
        self.label_3 = QtWidgets.QLabel(self.verticalFrame_8)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_8.addWidget(self.label_3)
        self.line_24 = QtWidgets.QFrame(self.verticalFrame_8)
        self.line_24.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.verticalLayout_8.addWidget(self.line_24)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem4)
        self.label_4 = QtWidgets.QLabel(self.verticalFrame_8)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.line_23 = QtWidgets.QFrame(self.verticalFrame_8)
        self.line_23.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.verticalLayout_8.addWidget(self.line_23)
        self.label_5 = QtWidgets.QLabel(self.verticalFrame_8)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_8.addWidget(self.label_5)
        self.line_22 = QtWidgets.QFrame(self.verticalFrame_8)
        self.line_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.verticalLayout_8.addWidget(self.line_22)
        self.label_6 = QtWidgets.QLabel(self.verticalFrame_8)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.horizontalLayout_2.addWidget(self.verticalFrame_8)
        self.verticalFrame = QtWidgets.QFrame(self.horizontalFrame)
        self.verticalFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.amp1 = QtWidgets.QSlider(self.verticalFrame)
        self.amp1.setEnabled(True)
        self.amp1.setMinimumSize(QtCore.QSize(30, 100))
        self.amp1.setMaximumSize(QtCore.QSize(16777215, 120))
        self.amp1.setMinimum(-30)
        self.amp1.setMaximum(30)
        self.amp1.setOrientation(QtCore.Qt.Vertical)
        self.amp1.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.amp1.setTickInterval(3)
        self.amp1.setObjectName("amp1")
        self.verticalLayout.addWidget(self.amp1)
        self.line_3 = QtWidgets.QFrame(self.verticalFrame)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.frd1 = QtWidgets.QDial(self.verticalFrame)
        self.frd1.setEnabled(True)
        self.frd1.setMinimumSize(QtCore.QSize(30, 30))
        self.frd1.setMaximumSize(QtCore.QSize(30, 30))
        self.frd1.setMinimum(20)
        self.frd1.setMaximum(20000)
        self.frd1.setSingleStep(10)
        self.frd1.setObjectName("frd1")
        self.verticalLayout.addWidget(self.frd1)
        self.line = QtWidgets.QFrame(self.verticalFrame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.spd1 = QtWidgets.QDial(self.verticalFrame)
        self.spd1.setEnabled(True)
        self.spd1.setMaximumSize(QtCore.QSize(30, 30))
        self.spd1.setMinimum(1)
        self.spd1.setMaximum(500)
        self.spd1.setObjectName("spd1")
        self.verticalLayout.addWidget(self.spd1)
        self.line_2 = QtWidgets.QFrame(self.verticalFrame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.bnd1 = QtWidgets.QToolButton(self.verticalFrame)
        self.bnd1.setMinimumSize(QtCore.QSize(30, 0))
        self.bnd1.setCheckable(True)
        self.bnd1.setAutoRepeat(False)
        self.bnd1.setAutoExclusive(True)
        self.bnd1.setAutoRepeatDelay(10)
        self.bnd1.setObjectName("bnd1")
        self.buttonGroup = QtWidgets.QButtonGroup(Dsp_player_mainwindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.bnd1)
        self.verticalLayout.addWidget(self.bnd1)
        self.spd1.raise_()
        self.bnd1.raise_()
        self.amp1.raise_()
        self.frd1.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.horizontalLayout_2.addWidget(self.verticalFrame)
        self.verticalFrame_4 = QtWidgets.QFrame(self.horizontalFrame)
        self.verticalFrame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verticalFrame_4.setObjectName("verticalFrame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalFrame_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.amp2 = QtWidgets.QSlider(self.verticalFrame_4)
        self.amp2.setMinimumSize(QtCore.QSize(30, 100))
        self.amp2.setMaximumSize(QtCore.QSize(16777215, 120))
        self.amp2.setMinimum(-30)
        self.amp2.setMaximum(30)
        self.amp2.setOrientation(QtCore.Qt.Vertical)
        self.amp2.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.amp2.setTickInterval(3)
        self.amp2.setObjectName("amp2")
        self.verticalLayout_4.addWidget(self.amp2)
        self.line_4 = QtWidgets.QFrame(self.verticalFrame_4)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_4.addWidget(self.line_4)
        self.frd2 = QtWidgets.QDial(self.verticalFrame_4)
        self.frd2.setMinimumSize(QtCore.QSize(30, 30))
        self.frd2.setMaximumSize(QtCore.QSize(30, 30))
        self.frd2.setMinimum(20)
        self.frd2.setMaximum(20000)
        self.frd2.setSingleStep(10)
        self.frd2.setObjectName("frd2")
        self.verticalLayout_4.addWidget(self.frd2)
        self.line_5 = QtWidgets.QFrame(self.verticalFrame_4)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_4.addWidget(self.line_5)
        self.spd2 = QtWidgets.QDial(self.verticalFrame_4)
        self.spd2.setMaximumSize(QtCore.QSize(30, 30))
        self.spd2.setMinimum(1)
        self.spd2.setMaximum(500)
        self.spd2.setObjectName("spd2")
        self.verticalLayout_4.addWidget(self.spd2)
        self.line_6 = QtWidgets.QFrame(self.verticalFrame_4)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_4.addWidget(self.line_6)
        self.bnd2 = QtWidgets.QToolButton(self.verticalFrame_4)
        self.bnd2.setMinimumSize(QtCore.QSize(30, 0))
        self.bnd2.setCheckable(True)
        self.bnd2.setAutoExclusive(True)
        self.bnd2.setObjectName("bnd2")
        self.buttonGroup.addButton(self.bnd2)
        self.verticalLayout_4.addWidget(self.bnd2)
        self.horizontalLayout_2.addWidget(self.verticalFrame_4)
        self.verticalFrame_7 = QtWidgets.QFrame(self.horizontalFrame)
        self.verticalFrame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verticalFrame_7.setObjectName("verticalFrame_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalFrame_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.amp3 = QtWidgets.QSlider(self.verticalFrame_7)
        self.amp3.setMinimumSize(QtCore.QSize(30, 100))
        self.amp3.setMaximumSize(QtCore.QSize(16777215, 120))
        self.amp3.setMinimum(-30)
        self.amp3.setMaximum(30)
        self.amp3.setOrientation(QtCore.Qt.Vertical)
        self.amp3.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.amp3.setTickInterval(3)
        self.amp3.setObjectName("amp3")
        self.verticalLayout_7.addWidget(self.amp3)
        self.line_7 = QtWidgets.QFrame(self.verticalFrame_7)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_7.addWidget(self.line_7)
        self.frd3 = QtWidgets.QDial(self.verticalFrame_7)
        self.frd3.setMinimumSize(QtCore.QSize(30, 30))
        self.frd3.setMaximumSize(QtCore.QSize(30, 30))
        self.frd3.setMinimum(20)
        self.frd3.setMaximum(20000)
        self.frd3.setSingleStep(10)
        self.frd3.setObjectName("frd3")
        self.verticalLayout_7.addWidget(self.frd3)
        self.line_12 = QtWidgets.QFrame(self.verticalFrame_7)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.verticalLayout_7.addWidget(self.line_12)
        self.spd3 = QtWidgets.QDial(self.verticalFrame_7)
        self.spd3.setMaximumSize(QtCore.QSize(30, 30))
        self.spd3.setMinimum(1)
        self.spd3.setMaximum(500)
        self.spd3.setObjectName("spd3")
        self.verticalLayout_7.addWidget(self.spd3)
        self.line_17 = QtWidgets.QFrame(self.verticalFrame_7)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.verticalLayout_7.addWidget(self.line_17)
        self.bnd3 = QtWidgets.QToolButton(self.verticalFrame_7)
        self.bnd3.setMinimumSize(QtCore.QSize(30, 0))
        self.bnd3.setCheckable(True)
        self.bnd3.setAutoExclusive(True)
        self.bnd3.setObjectName("bnd3")
        self.buttonGroup.addButton(self.bnd3)
        self.verticalLayout_7.addWidget(self.bnd3)
        self.horizontalLayout_2.addWidget(self.verticalFrame_7)
        self.verticalFrame_3 = QtWidgets.QFrame(self.horizontalFrame)
        self.verticalFrame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verticalFrame_3.setObjectName("verticalFrame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalFrame_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.amp4 = QtWidgets.QSlider(self.verticalFrame_3)
        self.amp4.setMinimumSize(QtCore.QSize(30, 100))
        self.amp4.setMaximumSize(QtCore.QSize(16777215, 120))
        self.amp4.setMinimum(-30)
        self.amp4.setMaximum(30)
        self.amp4.setOrientation(QtCore.Qt.Vertical)
        self.amp4.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.amp4.setTickInterval(3)
        self.amp4.setObjectName("amp4")
        self.verticalLayout_3.addWidget(self.amp4)
        self.line_8 = QtWidgets.QFrame(self.verticalFrame_3)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_3.addWidget(self.line_8)
        self.frd4 = QtWidgets.QDial(self.verticalFrame_3)
        self.frd4.setMinimumSize(QtCore.QSize(30, 30))
        self.frd4.setMaximumSize(QtCore.QSize(30, 30))
        self.frd4.setMinimum(20)
        self.frd4.setMaximum(20000)
        self.frd4.setSingleStep(10)
        self.frd4.setObjectName("frd4")
        self.verticalLayout_3.addWidget(self.frd4)
        self.line_13 = QtWidgets.QFrame(self.verticalFrame_3)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.verticalLayout_3.addWidget(self.line_13)
        self.spd4 = QtWidgets.QDial(self.verticalFrame_3)
        self.spd4.setMaximumSize(QtCore.QSize(30, 30))
        self.spd4.setMinimum(1)
        self.spd4.setMaximum(500)
        self.spd4.setObjectName("spd4")
        self.verticalLayout_3.addWidget(self.spd4)
        self.line_18 = QtWidgets.QFrame(self.verticalFrame_3)
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.verticalLayout_3.addWidget(self.line_18)
        self.bnd4 = QtWidgets.QToolButton(self.verticalFrame_3)
        self.bnd4.setMinimumSize(QtCore.QSize(30, 0))
        self.bnd4.setCheckable(True)
        self.bnd4.setAutoExclusive(True)
        self.bnd4.setObjectName("bnd4")
        self.buttonGroup.addButton(self.bnd4)
        self.verticalLayout_3.addWidget(self.bnd4)
        self.horizontalLayout_2.addWidget(self.verticalFrame_3)
        self.verticalFrame_5 = QtWidgets.QFrame(self.horizontalFrame)
        self.verticalFrame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verticalFrame_5.setObjectName("verticalFrame_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalFrame_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.amp5 = QtWidgets.QSlider(self.verticalFrame_5)
        self.amp5.setMinimumSize(QtCore.QSize(30, 100))
        self.amp5.setMaximumSize(QtCore.QSize(16777215, 120))
        self.amp5.setMinimum(-30)
        self.amp5.setMaximum(30)
        self.amp5.setOrientation(QtCore.Qt.Vertical)
        self.amp5.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.amp5.setTickInterval(3)
        self.amp5.setObjectName("amp5")
        self.verticalLayout_5.addWidget(self.amp5)
        self.line_9 = QtWidgets.QFrame(self.verticalFrame_5)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_5.addWidget(self.line_9)
        self.frd5 = QtWidgets.QDial(self.verticalFrame_5)
        self.frd5.setMinimumSize(QtCore.QSize(30, 30))
        self.frd5.setMaximumSize(QtCore.QSize(30, 30))
        self.frd5.setMinimum(20)
        self.frd5.setMaximum(20000)
        self.frd5.setSingleStep(10)
        self.frd5.setObjectName("frd5")
        self.verticalLayout_5.addWidget(self.frd5)
        self.line_14 = QtWidgets.QFrame(self.verticalFrame_5)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.verticalLayout_5.addWidget(self.line_14)
        self.spd5 = QtWidgets.QDial(self.verticalFrame_5)
        self.spd5.setMaximumSize(QtCore.QSize(30, 30))
        self.spd5.setMinimum(1)
        self.spd5.setMaximum(500)
        self.spd5.setObjectName("spd5")
        self.verticalLayout_5.addWidget(self.spd5)
        self.line_19 = QtWidgets.QFrame(self.verticalFrame_5)
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.verticalLayout_5.addWidget(self.line_19)
        self.bnd5 = QtWidgets.QToolButton(self.verticalFrame_5)
        self.bnd5.setMinimumSize(QtCore.QSize(30, 0))
        self.bnd5.setCheckable(True)
        self.bnd5.setAutoExclusive(True)
        self.bnd5.setObjectName("bnd5")
        self.buttonGroup.addButton(self.bnd5)
        self.verticalLayout_5.addWidget(self.bnd5)
        self.horizontalLayout_2.addWidget(self.verticalFrame_5)
        self.verticalFrame_2 = QtWidgets.QFrame(self.horizontalFrame)
        self.verticalFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verticalFrame_2.setObjectName("verticalFrame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalFrame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.amp6 = QtWidgets.QSlider(self.verticalFrame_2)
        self.amp6.setMinimumSize(QtCore.QSize(30, 100))
        self.amp6.setMaximumSize(QtCore.QSize(16777215, 120))
        self.amp6.setMinimum(-30)
        self.amp6.setMaximum(30)
        self.amp6.setOrientation(QtCore.Qt.Vertical)
        self.amp6.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.amp6.setTickInterval(3)
        self.amp6.setObjectName("amp6")
        self.verticalLayout_2.addWidget(self.amp6)
        self.line_10 = QtWidgets.QFrame(self.verticalFrame_2)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_2.addWidget(self.line_10)
        self.frd6 = QtWidgets.QDial(self.verticalFrame_2)
        self.frd6.setMinimumSize(QtCore.QSize(30, 30))
        self.frd6.setMaximumSize(QtCore.QSize(30, 30))
        self.frd6.setMinimum(20)
        self.frd6.setMaximum(20000)
        self.frd6.setSingleStep(10)
        self.frd6.setObjectName("frd6")
        self.verticalLayout_2.addWidget(self.frd6)
        self.line_15 = QtWidgets.QFrame(self.verticalFrame_2)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.verticalLayout_2.addWidget(self.line_15)
        self.spd6 = QtWidgets.QDial(self.verticalFrame_2)
        self.spd6.setMaximumSize(QtCore.QSize(30, 30))
        self.spd6.setMinimum(1)
        self.spd6.setMaximum(500)
        self.spd6.setObjectName("spd6")
        self.verticalLayout_2.addWidget(self.spd6)
        self.line_20 = QtWidgets.QFrame(self.verticalFrame_2)
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.verticalLayout_2.addWidget(self.line_20)
        self.bnd6 = QtWidgets.QToolButton(self.verticalFrame_2)
        self.bnd6.setMinimumSize(QtCore.QSize(30, 0))
        self.bnd6.setCheckable(True)
        self.bnd6.setAutoExclusive(True)
        self.bnd6.setObjectName("bnd6")
        self.buttonGroup.addButton(self.bnd6)
        self.verticalLayout_2.addWidget(self.bnd6)
        self.horizontalLayout_2.addWidget(self.verticalFrame_2)
        self.verticalFrame_6 = QtWidgets.QFrame(self.horizontalFrame)
        self.verticalFrame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verticalFrame_6.setObjectName("verticalFrame_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalFrame_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.amp7 = QtWidgets.QSlider(self.verticalFrame_6)
        self.amp7.setMinimumSize(QtCore.QSize(30, 100))
        self.amp7.setMaximumSize(QtCore.QSize(16777215, 120))
        self.amp7.setMinimum(-30)
        self.amp7.setMaximum(30)
        self.amp7.setOrientation(QtCore.Qt.Vertical)
        self.amp7.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.amp7.setTickInterval(3)
        self.amp7.setObjectName("amp7")
        self.verticalLayout_6.addWidget(self.amp7)
        self.line_11 = QtWidgets.QFrame(self.verticalFrame_6)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout_6.addWidget(self.line_11)
        self.frd7 = QtWidgets.QDial(self.verticalFrame_6)
        self.frd7.setMinimumSize(QtCore.QSize(30, 30))
        self.frd7.setMaximumSize(QtCore.QSize(30, 30))
        self.frd7.setMinimum(20)
        self.frd7.setMaximum(20000)
        self.frd7.setSingleStep(10)
        self.frd7.setObjectName("frd7")
        self.verticalLayout_6.addWidget(self.frd7)
        self.line_16 = QtWidgets.QFrame(self.verticalFrame_6)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.verticalLayout_6.addWidget(self.line_16)
        self.spd7 = QtWidgets.QDial(self.verticalFrame_6)
        self.spd7.setMaximumSize(QtCore.QSize(30, 30))
        self.spd7.setMinimum(1)
        self.spd7.setMaximum(500)
        self.spd7.setObjectName("spd7")
        self.verticalLayout_6.addWidget(self.spd7)
        self.line_21 = QtWidgets.QFrame(self.verticalFrame_6)
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.verticalLayout_6.addWidget(self.line_21)
        self.bnd7 = QtWidgets.QToolButton(self.verticalFrame_6)
        self.bnd7.setMinimumSize(QtCore.QSize(30, 0))
        self.bnd7.setCheckable(True)
        self.bnd7.setAutoExclusive(True)
        self.bnd7.setObjectName("bnd7")
        self.buttonGroup.addButton(self.bnd7)
        self.verticalLayout_6.addWidget(self.bnd7)
        self.horizontalLayout_2.addWidget(self.verticalFrame_6)
        self.frame = QtWidgets.QFrame(self.horizontalFrame)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setObjectName("frame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.amp_dial = QtWidgets.QDial(self.frame)
        self.amp_dial.setMinimumSize(QtCore.QSize(60, 60))
        self.amp_dial.setMaximumSize(QtCore.QSize(75, 75))
        self.amp_dial.setOrientation(QtCore.Qt.Horizontal)
        self.amp_dial.setInvertedAppearance(False)
        self.amp_dial.setInvertedControls(False)
        self.amp_dial.setWrapping(False)
        self.amp_dial.setNotchTarget(3.7)
        self.amp_dial.setNotchesVisible(True)
        self.amp_dial.setObjectName("amp_dial")
        self.verticalLayout_9.addWidget(self.amp_dial)
        self.line_26 = QtWidgets.QFrame(self.frame)
        self.line_26.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.verticalLayout_9.addWidget(self.line_26)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_9.addWidget(self.label_2)
        self.pan_diial = QtWidgets.QDial(self.frame)
        self.pan_diial.setMaximumSize(QtCore.QSize(75, 75))
        self.pan_diial.setProperty("value", 50)
        self.pan_diial.setNotchTarget(10.0)
        self.pan_diial.setNotchesVisible(True)
        self.pan_diial.setObjectName("pan_diial")
        self.verticalLayout_9.addWidget(self.pan_diial)
        self.line_25 = QtWidgets.QFrame(self.frame)
        self.line_25.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.verticalLayout_9.addWidget(self.line_25)
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_9.addWidget(self.label_10)
        self.horizontalLayout_2.addWidget(self.frame)
        self.gridLayout_5.addWidget(self.horizontalFrame, 1, 0, 1, 1)
        self.eq_graph = QtWidgets.QGraphicsView(self.tab)
        self.eq_graph.setObjectName("eq_graph")
        self.gridLayout_5.addWidget(self.eq_graph, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.server_on_toolB = QtWidgets.QToolButton(self.outer_frame_grid)
        self.server_on_toolB.setMinimumSize(QtCore.QSize(40, 0))
        self.server_on_toolB.setMaximumSize(QtCore.QSize(70, 16777215))
        self.server_on_toolB.setObjectName("server_on_toolB")
        self.horizontalLayout.addWidget(self.server_on_toolB)
        self.server_off_toolB = QtWidgets.QToolButton(self.outer_frame_grid)
        self.server_off_toolB.setMinimumSize(QtCore.QSize(40, 0))
        self.server_off_toolB.setMaximumSize(QtCore.QSize(70, 16777215))
        self.server_off_toolB.setObjectName("server_off_toolB")
        self.horizontalLayout.addWidget(self.server_off_toolB)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.outer_frame_grid, 0, 0, 1, 1)
        Dsp_player_mainwindow.setCentralWidget(self.centralwidget)
        self.actionSettings = QtWidgets.QAction(Dsp_player_mainwindow)
        self.actionSettings.setObjectName("actionSettings")

        self.retranslateUi(Dsp_player_mainwindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dsp_player_mainwindow)

    def retranslateUi(self, Dsp_player_mainwindow):
        _translate = QtCore.QCoreApplication.translate
        Dsp_player_mainwindow.setWindowTitle(_translate("Dsp_player_mainwindow", "DSP PLayer"))
        self.comboBox.setItemText(0, _translate("Dsp_player_mainwindow", "Flat"))
        self.comboBox.setItemText(1, _translate("Dsp_player_mainwindow", "Bass"))
        self.EnableB.setText(_translate("Dsp_player_mainwindow", "Enable"))
        self.DisableB.setText(_translate("Dsp_player_mainwindow", "Disable"))
        self.label_9.setText(_translate("Dsp_player_mainwindow", "High shelf"))
        self.hp_2.setText(_translate("Dsp_player_mainwindow", "2"))
        self.hp_3.setText(_translate("Dsp_player_mainwindow", "2"))
        self.hp_4.setText(_translate("Dsp_player_mainwindow", "2"))
        self.hp_5.setText(_translate("Dsp_player_mainwindow", "2"))
        self.hp_6.setText(_translate("Dsp_player_mainwindow", "2"))
        self.hp_7.setText(_translate("Dsp_player_mainwindow", "2"))
        self.hp_8.setText(_translate("Dsp_player_mainwindow", "2"))
        self.label_8.setText(_translate("Dsp_player_mainwindow", "Low shelf"))
        self.lp_2.setText(_translate("Dsp_player_mainwindow", "1"))
        self.lp_3.setText(_translate("Dsp_player_mainwindow", "1"))
        self.lp_5.setText(_translate("Dsp_player_mainwindow", "1"))
        self.lp_4.setText(_translate("Dsp_player_mainwindow", "1"))
        self.lp_6.setText(_translate("Dsp_player_mainwindow", "1"))
        self.lp_7.setText(_translate("Dsp_player_mainwindow", "1"))
        self.lp_8.setText(_translate("Dsp_player_mainwindow", "1"))
        self.label_7.setText(_translate("Dsp_player_mainwindow", "Peak/Notch"))
        self.pn_2.setText(_translate("Dsp_player_mainwindow", "0"))
        self.pn_3.setText(_translate("Dsp_player_mainwindow", "0"))
        self.pn_4.setText(_translate("Dsp_player_mainwindow", "0"))
        self.pn_5.setText(_translate("Dsp_player_mainwindow", "0"))
        self.pn_6.setText(_translate("Dsp_player_mainwindow", "0"))
        self.pn_7.setText(_translate("Dsp_player_mainwindow", "0"))
        self.pn_8.setText(_translate("Dsp_player_mainwindow", "0"))
        self.label_3.setText(_translate("Dsp_player_mainwindow", "Amp"))
        self.label_4.setText(_translate("Dsp_player_mainwindow", "Freq"))
        self.label_5.setText(_translate("Dsp_player_mainwindow", "Spred"))
        self.label_6.setText(_translate("Dsp_player_mainwindow", "Band"))
        self.bnd1.setText(_translate("Dsp_player_mainwindow", "1"))
        self.bnd2.setText(_translate("Dsp_player_mainwindow", "2"))
        self.bnd3.setText(_translate("Dsp_player_mainwindow", "3"))
        self.bnd4.setText(_translate("Dsp_player_mainwindow", "4"))
        self.bnd5.setText(_translate("Dsp_player_mainwindow", "5"))
        self.bnd6.setText(_translate("Dsp_player_mainwindow", "6"))
        self.bnd7.setText(_translate("Dsp_player_mainwindow", "7"))
        self.label_2.setText(_translate("Dsp_player_mainwindow", "Master"))
        self.label_10.setText(_translate("Dsp_player_mainwindow", "Pan"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dsp_player_mainwindow", "Parametric EQ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dsp_player_mainwindow", "Tab 2"))
        self.server_on_toolB.setText(_translate("Dsp_player_mainwindow", "Server On"))
        self.server_off_toolB.setText(_translate("Dsp_player_mainwindow", "Server Off"))
        self.actionSettings.setText(_translate("Dsp_player_mainwindow", "Settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dsp_player_mainwindow = QtWidgets.QMainWindow()
    ui = Ui_Dsp_player_mainwindow()
    ui.setupUi(Dsp_player_mainwindow)
    Dsp_player_mainwindow.show()
    sys.exit(app.exec_())
