# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\dsp_player.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dsp_player_mainwindow(object):
    def setupUi(self, Dsp_player_mainwindow):
        Dsp_player_mainwindow.setObjectName("Dsp_player_mainwindow")
        Dsp_player_mainwindow.setWindowModality(QtCore.Qt.ApplicationModal)
        Dsp_player_mainwindow.resize(895, 729)
        Dsp_player_mainwindow.setMinimumSize(QtCore.QSize(895, 729))
        Dsp_player_mainwindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(Dsp_player_mainwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.outer_frame_grid = QtWidgets.QFrame(self.centralwidget)
        self.outer_frame_grid.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.outer_frame_grid.setObjectName("outer_frame_grid")
        self.gridLayout = QtWidgets.QGridLayout(self.outer_frame_grid)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.outer_frame_grid)
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.outer_frame_grid)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setObjectName("tabWidget")
        self.para_eq = QtWidgets.QWidget()
        self.para_eq.setObjectName("para_eq")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.para_eq)
        self.gridLayout_5.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_5.setSpacing(4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalFrame = QtWidgets.QFrame(self.para_eq)
        self.horizontalFrame.setMaximumSize(QtCore.QSize(16777215, 204))
        self.horizontalFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.horizontalFrame)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setObjectName("frame")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_11.addWidget(self.comboBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.EnableB = QtWidgets.QToolButton(self.frame)
        self.EnableB.setCheckable(True)
        self.EnableB.setAutoExclusive(True)
        self.EnableB.setObjectName("EnableB")
        self.buttonGroup_9 = QtWidgets.QButtonGroup(Dsp_player_mainwindow)
        self.buttonGroup_9.setObjectName("buttonGroup_9")
        self.buttonGroup_9.addButton(self.EnableB)
        self.horizontalLayout_6.addWidget(self.EnableB)
        self.DisableB = QtWidgets.QToolButton(self.frame)
        self.DisableB.setCheckable(True)
        self.DisableB.setAutoExclusive(True)
        self.DisableB.setObjectName("DisableB")
        self.buttonGroup_9.addButton(self.DisableB)
        self.horizontalLayout_6.addWidget(self.DisableB)
        self.verticalLayout_11.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2.addWidget(self.frame)
        self.frame1 = QtWidgets.QFrame(self.horizontalFrame)
        self.frame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame1.setObjectName("frame1")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame1)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_9 = QtWidgets.QLabel(self.frame1)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.hp_2 = QtWidgets.QToolButton(self.frame1)
        self.hp_2.setMinimumSize(QtCore.QSize(25, 25))
        self.hp_2.setIconSize(QtCore.QSize(25, 25))
        self.hp_2.setCheckable(True)
        self.hp_2.setAutoExclusive(True)
        self.hp_2.setObjectName("hp_2")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(Dsp_player_mainwindow)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.hp_2)
        self.horizontalLayout_3.addWidget(self.hp_2)
        self.hp_3 = QtWidgets.QToolButton(self.frame1)
        self.hp_3.setMinimumSize(QtCore.QSize(25, 25))
        self.hp_3.setCheckable(True)
        self.hp_3.setAutoExclusive(True)
        self.hp_3.setObjectName("hp_3")
        self.buttonGroup_3 = QtWidgets.QButtonGroup(Dsp_player_mainwindow)
        self.buttonGroup_3.setObjectName("buttonGroup_3")
        self.buttonGroup_3.addButton(self.hp_3)
        self.horizontalLayout_3.addWidget(self.hp_3)
        self.hp_4 = QtWidgets.QToolButton(self.frame1)
        self.hp_4.setMinimumSize(QtCore.QSize(25, 25))
        self.hp_4.setIconSize(QtCore.QSize(25, 25))
        self.hp_4.setCheckable(True)
        self.hp_4.setAutoExclusive(True)
        self.hp_4.setObjectName("hp_4")
        self.buttonGroup_4 = QtWidgets.QButtonGroup(Dsp_player_mainwindow)
        self.buttonGroup_4.setObjectName("buttonGroup_4")
        self.buttonGroup_4.addButton(self.hp_4)
        self.horizontalLayout_3.addWidget(self.hp_4)
        self.hp_5 = QtWidgets.QToolButton(self.frame1)
        self.hp_5.setMinimumSize(QtCore.QSize(25, 25))
        self.hp_5.setIconSize(QtCore.QSize(25, 25))
        self.hp_5.setCheckable(True)
        self.hp_5.setAutoExclusive(True)
        self.hp_5.setObjectName("hp_5")
        self.buttonGroup_5 = QtWidgets.QButtonGroup(Dsp_player_mainwindow)
        self.buttonGroup_5.setObjectName("buttonGroup_5")
        self.buttonGroup_5.addButton(self.hp_5)
        self.horizontalLayout_3.addWidget(self.hp_5)
        self.hp_6 = QtWidgets.QToolButton(self.frame1)
        self.hp_6.setMinimumSize(QtCore.QSize(25, 25))
        self.hp_6.setIconSize(QtCore.QSize(25, 25))
        self.hp_6.setCheckable(True)
        self.hp_6.setAutoExclusive(True)
        self.hp_6.setObjectName("hp_6")
        self.buttonGroup_6 = QtWidgets.QButtonGroup(Dsp_player_mainwindow)
        self.buttonGroup_6.setObjectName("buttonGroup_6")
        self.buttonGroup_6.addButton(self.hp_6)
        self.horizontalLayout_3.addWidget(self.hp_6)
        self.hp_7 = QtWidgets.QToolButton(self.frame1)
        self.hp_7.setMinimumSize(QtCore.QSize(25, 25))
        self.hp_7.setIconSize(QtCore.QSize(25, 25))
        self.hp_7.setCheckable(True)
        self.hp_7.setAutoExclusive(True)
        self.hp_7.setObjectName("hp_7")
        self.buttonGroup_7 = QtWidgets.QButtonGroup(Dsp_player_mainwindow)
        self.buttonGroup_7.setObjectName("buttonGroup_7")
        self.buttonGroup_7.addButton(self.hp_7)
        self.horizontalLayout_3.addWidget(self.hp_7)
        self.hp_8 = QtWidgets.QToolButton(self.frame1)
        self.hp_8.setMinimumSize(QtCore.QSize(25, 25))
        self.hp_8.setIconSize(QtCore.QSize(25, 25))
        self.hp_8.setCheckable(True)
        self.hp_8.setAutoExclusive(True)
        self.hp_8.setObjectName("hp_8")
        self.buttonGroup_8 = QtWidgets.QButtonGroup(Dsp_player_mainwindow)
        self.buttonGroup_8.setObjectName("buttonGroup_8")
        self.buttonGroup_8.addButton(self.hp_8)
        self.horizontalLayout_3.addWidget(self.hp_8)
        self.verticalLayout_10.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.frame1)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.lp_2 = QtWidgets.QToolButton(self.frame1)
        self.lp_2.setMinimumSize(QtCore.QSize(25, 25))
        self.lp_2.setIconSize(QtCore.QSize(25, 25))
        self.lp_2.setCheckable(True)
        self.lp_2.setAutoExclusive(True)
        self.lp_2.setObjectName("lp_2")
        self.buttonGroup_2.addButton(self.lp_2)
        self.horizontalLayout_4.addWidget(self.lp_2)
        self.lp_3 = QtWidgets.QToolButton(self.frame1)
        self.lp_3.setMinimumSize(QtCore.QSize(25, 25))
        self.lp_3.setIconSize(QtCore.QSize(25, 25))
        self.lp_3.setCheckable(True)
        self.lp_3.setAutoExclusive(True)
        self.lp_3.setObjectName("lp_3")
        self.buttonGroup_3.addButton(self.lp_3)
        self.horizontalLayout_4.addWidget(self.lp_3)
        self.lp_5 = QtWidgets.QToolButton(self.frame1)
        self.lp_5.setMinimumSize(QtCore.QSize(25, 25))
        self.lp_5.setIconSize(QtCore.QSize(25, 25))
        self.lp_5.setCheckable(True)
        self.lp_5.setAutoExclusive(True)
        self.lp_5.setObjectName("lp_5")
        self.buttonGroup_4.addButton(self.lp_5)
        self.horizontalLayout_4.addWidget(self.lp_5)
        self.lp_4 = QtWidgets.QToolButton(self.frame1)
        self.lp_4.setMinimumSize(QtCore.QSize(25, 25))
        self.lp_4.setIconSize(QtCore.QSize(25, 25))
        self.lp_4.setCheckable(True)
        self.lp_4.setAutoExclusive(True)
        self.lp_4.setObjectName("lp_4")
        self.buttonGroup_5.addButton(self.lp_4)
        self.horizontalLayout_4.addWidget(self.lp_4)
        self.lp_6 = QtWidgets.QToolButton(self.frame1)
        self.lp_6.setMinimumSize(QtCore.QSize(25, 25))
        self.lp_6.setIconSize(QtCore.QSize(25, 25))
        self.lp_6.setCheckable(True)
        self.lp_6.setAutoExclusive(True)
        self.lp_6.setObjectName("lp_6")
        self.buttonGroup_6.addButton(self.lp_6)
        self.horizontalLayout_4.addWidget(self.lp_6)
        self.lp_7 = QtWidgets.QToolButton(self.frame1)
        self.lp_7.setMinimumSize(QtCore.QSize(25, 25))
        self.lp_7.setIconSize(QtCore.QSize(25, 25))
        self.lp_7.setCheckable(True)
        self.lp_7.setAutoExclusive(True)
        self.lp_7.setObjectName("lp_7")
        self.buttonGroup_7.addButton(self.lp_7)
        self.horizontalLayout_4.addWidget(self.lp_7)
        self.lp_8 = QtWidgets.QToolButton(self.frame1)
        self.lp_8.setMinimumSize(QtCore.QSize(25, 25))
        self.lp_8.setIconSize(QtCore.QSize(25, 25))
        self.lp_8.setCheckable(True)
        self.lp_8.setAutoExclusive(True)
        self.lp_8.setObjectName("lp_8")
        self.buttonGroup_8.addButton(self.lp_8)
        self.horizontalLayout_4.addWidget(self.lp_8)
        self.verticalLayout_10.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.frame1)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.pn_2 = QtWidgets.QToolButton(self.frame1)
        self.pn_2.setMinimumSize(QtCore.QSize(25, 25))
        self.pn_2.setIconSize(QtCore.QSize(25, 25))
        self.pn_2.setCheckable(True)
        self.pn_2.setChecked(True)
        self.pn_2.setAutoExclusive(True)
        self.pn_2.setObjectName("pn_2")
        self.buttonGroup_2.addButton(self.pn_2)
        self.horizontalLayout_5.addWidget(self.pn_2)
        self.pn_3 = QtWidgets.QToolButton(self.frame1)
        self.pn_3.setMinimumSize(QtCore.QSize(25, 25))
        self.pn_3.setIconSize(QtCore.QSize(25, 25))
        self.pn_3.setCheckable(True)
        self.pn_3.setChecked(True)
        self.pn_3.setAutoExclusive(True)
        self.pn_3.setObjectName("pn_3")
        self.buttonGroup_3.addButton(self.pn_3)
        self.horizontalLayout_5.addWidget(self.pn_3)
        self.pn_4 = QtWidgets.QToolButton(self.frame1)
        self.pn_4.setMinimumSize(QtCore.QSize(25, 25))
        self.pn_4.setIconSize(QtCore.QSize(25, 25))
        self.pn_4.setCheckable(True)
        self.pn_4.setChecked(True)
        self.pn_4.setAutoExclusive(True)
        self.pn_4.setObjectName("pn_4")
        self.buttonGroup_4.addButton(self.pn_4)
        self.horizontalLayout_5.addWidget(self.pn_4)
        self.pn_5 = QtWidgets.QToolButton(self.frame1)
        self.pn_5.setMinimumSize(QtCore.QSize(25, 25))
        self.pn_5.setIconSize(QtCore.QSize(25, 25))
        self.pn_5.setCheckable(True)
        self.pn_5.setChecked(True)
        self.pn_5.setAutoExclusive(True)
        self.pn_5.setObjectName("pn_5")
        self.buttonGroup_5.addButton(self.pn_5)
        self.horizontalLayout_5.addWidget(self.pn_5)
        self.pn_6 = QtWidgets.QToolButton(self.frame1)
        self.pn_6.setMinimumSize(QtCore.QSize(25, 25))
        self.pn_6.setIconSize(QtCore.QSize(25, 25))
        self.pn_6.setCheckable(True)
        self.pn_6.setChecked(True)
        self.pn_6.setAutoExclusive(True)
        self.pn_6.setObjectName("pn_6")
        self.buttonGroup_6.addButton(self.pn_6)
        self.horizontalLayout_5.addWidget(self.pn_6)
        self.pn_7 = QtWidgets.QToolButton(self.frame1)
        self.pn_7.setMinimumSize(QtCore.QSize(25, 25))
        self.pn_7.setIconSize(QtCore.QSize(25, 25))
        self.pn_7.setCheckable(True)
        self.pn_7.setChecked(True)
        self.pn_7.setAutoExclusive(True)
        self.pn_7.setObjectName("pn_7")
        self.buttonGroup_7.addButton(self.pn_7)
        self.horizontalLayout_5.addWidget(self.pn_7)
        self.pn_8 = QtWidgets.QToolButton(self.frame1)
        self.pn_8.setMinimumSize(QtCore.QSize(25, 25))
        self.pn_8.setIconSize(QtCore.QSize(25, 25))
        self.pn_8.setCheckable(True)
        self.pn_8.setChecked(True)
        self.pn_8.setAutoExclusive(True)
        self.pn_8.setObjectName("pn_8")
        self.buttonGroup_8.addButton(self.pn_8)
        self.horizontalLayout_5.addWidget(self.pn_8)
        self.verticalLayout_10.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2.addWidget(self.frame1)
        self.verticalFrame_8 = QtWidgets.QFrame(self.horizontalFrame)
        self.verticalFrame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verticalFrame_8.setObjectName("verticalFrame_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalFrame_8)
        self.verticalLayout_8.setContentsMargins(1, 0, 1, 0)
        self.verticalLayout_8.setSpacing(10)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem3 = QtWidgets.QSpacerItem(20, 39, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem3)
        self.label_3 = QtWidgets.QLabel(self.verticalFrame_8)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_8.addWidget(self.label_3)
        self.line_24 = QtWidgets.QFrame(self.verticalFrame_8)
        self.line_24.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.verticalLayout_8.addWidget(self.line_24)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem4)
        self.label_4 = QtWidgets.QLabel(self.verticalFrame_8)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.line_23 = QtWidgets.QFrame(self.verticalFrame_8)
        self.line_23.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.verticalLayout_8.addWidget(self.line_23)
        self.label_5 = QtWidgets.QLabel(self.verticalFrame_8)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_8.addWidget(self.label_5)
        self.line_22 = QtWidgets.QFrame(self.verticalFrame_8)
        self.line_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.verticalLayout_8.addWidget(self.line_22)
        self.label_6 = QtWidgets.QLabel(self.verticalFrame_8)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.horizontalLayout_2.addWidget(self.verticalFrame_8)
        self.verticalFrame = QtWidgets.QFrame(self.horizontalFrame)
        self.verticalFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.amp1 = QtWidgets.QSlider(self.verticalFrame)
        self.amp1.setEnabled(True)
        self.amp1.setMinimumSize(QtCore.QSize(30, 100))
        self.amp1.setMaximumSize(QtCore.QSize(16777215, 120))
        self.amp1.setMinimum(-30)
        self.amp1.setMaximum(30)
        self.amp1.setOrientation(QtCore.Qt.Vertical)
        self.amp1.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.amp1.setTickInterval(3)
        self.amp1.setObjectName("amp1")
        self.verticalLayout.addWidget(self.amp1)
        self.line_3 = QtWidgets.QFrame(self.verticalFrame)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.frd1 = QtWidgets.QDial(self.verticalFrame)
        self.frd1.setEnabled(True)
        self.frd1.setMinimumSize(QtCore.QSize(30, 30))
        self.frd1.setMaximumSize(QtCore.QSize(30, 30))
        self.frd1.setMinimum(20)
        self.frd1.setMaximum(20000)
        self.frd1.setSingleStep(10)
        self.frd1.setObjectName("frd1")
        self.verticalLayout.addWidget(self.frd1)
        self.line = QtWidgets.QFrame(self.verticalFrame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.spd1 = QtWidgets.QDial(self.verticalFrame)
        self.spd1.setEnabled(True)
        self.spd1.setMaximumSize(QtCore.QSize(30, 30))
        self.spd1.setMinimum(1)
        self.spd1.setMaximum(500)
        self.spd1.setObjectName("spd1")
        self.verticalLayout.addWidget(self.spd1)
        self.line_2 = QtWidgets.QFrame(self.verticalFrame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.bnd1 = QtWidgets.QToolButton(self.verticalFrame)
        self.bnd1.setMinimumSize(QtCore.QSize(30, 0))
        self.bnd1.setCheckable(True)
        self.bnd1.setAutoRepeat(False)
        self.bnd1.setAutoExclusive(True)
        self.bnd1.setAutoRepeatDelay(10)
        self.bnd1.setObjectName("bnd1")
        self.buttonGroup = QtWidgets.QButtonGroup(Dsp_player_mainwindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.bnd1)
        self.verticalLayout.addWidget(self.bnd1)
        self.spd1.raise_()
        self.bnd1.raise_()
        self.amp1.raise_()
        self.frd1.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.horizontalLayout_2.addWidget(self.verticalFrame)
        self.verticalFrame_4 = QtWidgets.QFrame(self.horizontalFrame)
        self.verticalFrame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verticalFrame_4.setObjectName("verticalFrame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalFrame_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.amp2 = QtWidgets.QSlider(self.verticalFrame_4)
        self.amp2.setMinimumSize(QtCore.QSize(30, 100))
        self.amp2.setMaximumSize(QtCore.QSize(16777215, 120))
        self.amp2.setMinimum(-30)
        self.amp2.setMaximum(30)
        self.amp2.setOrientation(QtCore.Qt.Vertical)
        self.amp2.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.amp2.setTickInterval(3)
        self.amp2.setObjectName("amp2")
        self.verticalLayout_4.addWidget(self.amp2)
        self.line_4 = QtWidgets.QFrame(self.verticalFrame_4)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_4.addWidget(self.line_4)
        self.frd2 = QtWidgets.QDial(self.verticalFrame_4)
        self.frd2.setMinimumSize(QtCore.QSize(30, 30))
        self.frd2.setMaximumSize(QtCore.QSize(30, 30))
        self.frd2.setMinimum(20)
        self.frd2.setMaximum(20000)
        self.frd2.setSingleStep(10)
        self.frd2.setObjectName("frd2")
        self.verticalLayout_4.addWidget(self.frd2)
        self.line_5 = QtWidgets.QFrame(self.verticalFrame_4)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_4.addWidget(self.line_5)
        self.spd2 = QtWidgets.QDial(self.verticalFrame_4)
        self.spd2.setMaximumSize(QtCore.QSize(30, 30))
        self.spd2.setMinimum(1)
        self.spd2.setMaximum(500)
        self.spd2.setObjectName("spd2")
        self.verticalLayout_4.addWidget(self.spd2)
        self.line_6 = QtWidgets.QFrame(self.verticalFrame_4)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_4.addWidget(self.line_6)
        self.bnd2 = QtWidgets.QToolButton(self.verticalFrame_4)
        self.bnd2.setMinimumSize(QtCore.QSize(30, 0))
        self.bnd2.setCheckable(True)
        self.bnd2.setAutoExclusive(True)
        self.bnd2.setObjectName("bnd2")
        self.buttonGroup.addButton(self.bnd2)
        self.verticalLayout_4.addWidget(self.bnd2)
        self.horizontalLayout_2.addWidget(self.verticalFrame_4)
        self.verticalFrame_7 = QtWidgets.QFrame(self.horizontalFrame)
        self.verticalFrame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verticalFrame_7.setObjectName("verticalFrame_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalFrame_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.amp3 = QtWidgets.QSlider(self.verticalFrame_7)
        self.amp3.setMinimumSize(QtCore.QSize(30, 100))
        self.amp3.setMaximumSize(QtCore.QSize(16777215, 120))
        self.amp3.setMinimum(-30)
        self.amp3.setMaximum(30)
        self.amp3.setOrientation(QtCore.Qt.Vertical)
        self.amp3.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.amp3.setTickInterval(3)
        self.amp3.setObjectName("amp3")
        self.verticalLayout_7.addWidget(self.amp3)
        self.line_7 = QtWidgets.QFrame(self.verticalFrame_7)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_7.addWidget(self.line_7)
        self.frd3 = QtWidgets.QDial(self.verticalFrame_7)
        self.frd3.setMinimumSize(QtCore.QSize(30, 30))
        self.frd3.setMaximumSize(QtCore.QSize(30, 30))
        self.frd3.setMinimum(20)
        self.frd3.setMaximum(20000)
        self.frd3.setSingleStep(10)
        self.frd3.setObjectName("frd3")
        self.verticalLayout_7.addWidget(self.frd3)
        self.line_12 = QtWidgets.QFrame(self.verticalFrame_7)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.verticalLayout_7.addWidget(self.line_12)
        self.spd3 = QtWidgets.QDial(self.verticalFrame_7)
        self.spd3.setMaximumSize(QtCore.QSize(30, 30))
        self.spd3.setMinimum(1)
        self.spd3.setMaximum(500)
        self.spd3.setObjectName("spd3")
        self.verticalLayout_7.addWidget(self.spd3)
        self.line_17 = QtWidgets.QFrame(self.verticalFrame_7)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.verticalLayout_7.addWidget(self.line_17)
        self.bnd3 = QtWidgets.QToolButton(self.verticalFrame_7)
        self.bnd3.setMinimumSize(QtCore.QSize(30, 0))
        self.bnd3.setCheckable(True)
        self.bnd3.setAutoExclusive(True)
        self.bnd3.setObjectName("bnd3")
        self.buttonGroup.addButton(self.bnd3)
        self.verticalLayout_7.addWidget(self.bnd3)
        self.horizontalLayout_2.addWidget(self.verticalFrame_7)
        self.verticalFrame_3 = QtWidgets.QFrame(self.horizontalFrame)
        self.verticalFrame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verticalFrame_3.setObjectName("verticalFrame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalFrame_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.amp4 = QtWidgets.QSlider(self.verticalFrame_3)
        self.amp4.setMinimumSize(QtCore.QSize(30, 100))
        self.amp4.setMaximumSize(QtCore.QSize(16777215, 120))
        self.amp4.setMinimum(-30)
        self.amp4.setMaximum(30)
        self.amp4.setOrientation(QtCore.Qt.Vertical)
        self.amp4.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.amp4.setTickInterval(3)
        self.amp4.setObjectName("amp4")
        self.verticalLayout_3.addWidget(self.amp4)
        self.line_8 = QtWidgets.QFrame(self.verticalFrame_3)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_3.addWidget(self.line_8)
        self.frd4 = QtWidgets.QDial(self.verticalFrame_3)
        self.frd4.setMinimumSize(QtCore.QSize(30, 30))
        self.frd4.setMaximumSize(QtCore.QSize(30, 30))
        self.frd4.setMinimum(20)
        self.frd4.setMaximum(20000)
        self.frd4.setSingleStep(10)
        self.frd4.setObjectName("frd4")
        self.verticalLayout_3.addWidget(self.frd4)
        self.line_13 = QtWidgets.QFrame(self.verticalFrame_3)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.verticalLayout_3.addWidget(self.line_13)
        self.spd4 = QtWidgets.QDial(self.verticalFrame_3)
        self.spd4.setMaximumSize(QtCore.QSize(30, 30))
        self.spd4.setMinimum(1)
        self.spd4.setMaximum(500)
        self.spd4.setObjectName("spd4")
        self.verticalLayout_3.addWidget(self.spd4)
        self.line_18 = QtWidgets.QFrame(self.verticalFrame_3)
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.verticalLayout_3.addWidget(self.line_18)
        self.bnd4 = QtWidgets.QToolButton(self.verticalFrame_3)
        self.bnd4.setMinimumSize(QtCore.QSize(30, 0))
        self.bnd4.setCheckable(True)
        self.bnd4.setAutoExclusive(True)
        self.bnd4.setObjectName("bnd4")
        self.buttonGroup.addButton(self.bnd4)
        self.verticalLayout_3.addWidget(self.bnd4)
        self.horizontalLayout_2.addWidget(self.verticalFrame_3)
        self.verticalFrame_5 = QtWidgets.QFrame(self.horizontalFrame)
        self.verticalFrame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verticalFrame_5.setObjectName("verticalFrame_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalFrame_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.amp5 = QtWidgets.QSlider(self.verticalFrame_5)
        self.amp5.setMinimumSize(QtCore.QSize(30, 100))
        self.amp5.setMaximumSize(QtCore.QSize(16777215, 120))
        self.amp5.setMinimum(-30)
        self.amp5.setMaximum(30)
        self.amp5.setOrientation(QtCore.Qt.Vertical)
        self.amp5.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.amp5.setTickInterval(3)
        self.amp5.setObjectName("amp5")
        self.verticalLayout_5.addWidget(self.amp5)
        self.line_9 = QtWidgets.QFrame(self.verticalFrame_5)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_5.addWidget(self.line_9)
        self.frd5 = QtWidgets.QDial(self.verticalFrame_5)
        self.frd5.setMinimumSize(QtCore.QSize(30, 30))
        self.frd5.setMaximumSize(QtCore.QSize(30, 30))
        self.frd5.setMinimum(20)
        self.frd5.setMaximum(20000)
        self.frd5.setSingleStep(10)
        self.frd5.setObjectName("frd5")
        self.verticalLayout_5.addWidget(self.frd5)
        self.line_14 = QtWidgets.QFrame(self.verticalFrame_5)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.verticalLayout_5.addWidget(self.line_14)
        self.spd5 = QtWidgets.QDial(self.verticalFrame_5)
        self.spd5.setMaximumSize(QtCore.QSize(30, 30))
        self.spd5.setMinimum(1)
        self.spd5.setMaximum(500)
        self.spd5.setObjectName("spd5")
        self.verticalLayout_5.addWidget(self.spd5)
        self.line_19 = QtWidgets.QFrame(self.verticalFrame_5)
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.verticalLayout_5.addWidget(self.line_19)
        self.bnd5 = QtWidgets.QToolButton(self.verticalFrame_5)
        self.bnd5.setMinimumSize(QtCore.QSize(30, 0))
        self.bnd5.setCheckable(True)
        self.bnd5.setAutoExclusive(True)
        self.bnd5.setObjectName("bnd5")
        self.buttonGroup.addButton(self.bnd5)
        self.verticalLayout_5.addWidget(self.bnd5)
        self.horizontalLayout_2.addWidget(self.verticalFrame_5)
        self.verticalFrame_2 = QtWidgets.QFrame(self.horizontalFrame)
        self.verticalFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verticalFrame_2.setObjectName("verticalFrame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalFrame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.amp6 = QtWidgets.QSlider(self.verticalFrame_2)
        self.amp6.setMinimumSize(QtCore.QSize(30, 100))
        self.amp6.setMaximumSize(QtCore.QSize(16777215, 120))
        self.amp6.setMinimum(-30)
        self.amp6.setMaximum(30)
        self.amp6.setOrientation(QtCore.Qt.Vertical)
        self.amp6.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.amp6.setTickInterval(3)
        self.amp6.setObjectName("amp6")
        self.verticalLayout_2.addWidget(self.amp6)
        self.line_10 = QtWidgets.QFrame(self.verticalFrame_2)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_2.addWidget(self.line_10)
        self.frd6 = QtWidgets.QDial(self.verticalFrame_2)
        self.frd6.setMinimumSize(QtCore.QSize(30, 30))
        self.frd6.setMaximumSize(QtCore.QSize(30, 30))
        self.frd6.setMinimum(20)
        self.frd6.setMaximum(20000)
        self.frd6.setSingleStep(10)
        self.frd6.setObjectName("frd6")
        self.verticalLayout_2.addWidget(self.frd6)
        self.line_15 = QtWidgets.QFrame(self.verticalFrame_2)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.verticalLayout_2.addWidget(self.line_15)
        self.spd6 = QtWidgets.QDial(self.verticalFrame_2)
        self.spd6.setMaximumSize(QtCore.QSize(30, 30))
        self.spd6.setMinimum(1)
        self.spd6.setMaximum(500)
        self.spd6.setObjectName("spd6")
        self.verticalLayout_2.addWidget(self.spd6)
        self.line_20 = QtWidgets.QFrame(self.verticalFrame_2)
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.verticalLayout_2.addWidget(self.line_20)
        self.bnd6 = QtWidgets.QToolButton(self.verticalFrame_2)
        self.bnd6.setMinimumSize(QtCore.QSize(30, 0))
        self.bnd6.setCheckable(True)
        self.bnd6.setAutoExclusive(True)
        self.bnd6.setObjectName("bnd6")
        self.buttonGroup.addButton(self.bnd6)
        self.verticalLayout_2.addWidget(self.bnd6)
        self.horizontalLayout_2.addWidget(self.verticalFrame_2)
        self.verticalFrame_6 = QtWidgets.QFrame(self.horizontalFrame)
        self.verticalFrame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verticalFrame_6.setObjectName("verticalFrame_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalFrame_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.amp7 = QtWidgets.QSlider(self.verticalFrame_6)
        self.amp7.setMinimumSize(QtCore.QSize(30, 100))
        self.amp7.setMaximumSize(QtCore.QSize(16777215, 120))
        self.amp7.setMinimum(-30)
        self.amp7.setMaximum(30)
        self.amp7.setOrientation(QtCore.Qt.Vertical)
        self.amp7.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.amp7.setTickInterval(3)
        self.amp7.setObjectName("amp7")
        self.verticalLayout_6.addWidget(self.amp7)
        self.line_11 = QtWidgets.QFrame(self.verticalFrame_6)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout_6.addWidget(self.line_11)
        self.frd7 = QtWidgets.QDial(self.verticalFrame_6)
        self.frd7.setMinimumSize(QtCore.QSize(30, 30))
        self.frd7.setMaximumSize(QtCore.QSize(30, 30))
        self.frd7.setMinimum(20)
        self.frd7.setMaximum(20000)
        self.frd7.setSingleStep(10)
        self.frd7.setObjectName("frd7")
        self.verticalLayout_6.addWidget(self.frd7)
        self.line_16 = QtWidgets.QFrame(self.verticalFrame_6)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.verticalLayout_6.addWidget(self.line_16)
        self.spd7 = QtWidgets.QDial(self.verticalFrame_6)
        self.spd7.setMaximumSize(QtCore.QSize(30, 30))
        self.spd7.setMinimum(1)
        self.spd7.setMaximum(500)
        self.spd7.setObjectName("spd7")
        self.verticalLayout_6.addWidget(self.spd7)
        self.line_21 = QtWidgets.QFrame(self.verticalFrame_6)
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.verticalLayout_6.addWidget(self.line_21)
        self.bnd7 = QtWidgets.QToolButton(self.verticalFrame_6)
        self.bnd7.setMinimumSize(QtCore.QSize(30, 0))
        self.bnd7.setCheckable(True)
        self.bnd7.setAutoExclusive(True)
        self.bnd7.setObjectName("bnd7")
        self.buttonGroup.addButton(self.bnd7)
        self.verticalLayout_6.addWidget(self.bnd7)
        self.horizontalLayout_2.addWidget(self.verticalFrame_6)
        self.gridLayout_5.addWidget(self.horizontalFrame, 1, 0, 1, 1)
        self.eq_graph = PlotWidget(self.para_eq)
        self.eq_graph.setEnabled(False)
        self.eq_graph.setMaximumSize(QtCore.QSize(4255, 16777215))
        self.eq_graph.setObjectName("eq_graph")
        self.gridLayout_5.addWidget(self.eq_graph, 0, 0, 1, 1)
        self.tabWidget.addTab(self.para_eq, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tabWidget.addTab(self.tab, "")
        self.pann = QtWidgets.QWidget()
        self.pann.setObjectName("pann")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.pann)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.graphicsView_span = QtWidgets.QGraphicsView(self.pann)
        self.graphicsView_span.setObjectName("graphicsView_span")
        self.gridLayout_6.addWidget(self.graphicsView_span, 1, 1, 1, 1)
        self.horizontalFrame1 = QtWidgets.QFrame(self.pann)
        self.horizontalFrame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.horizontalFrame1.setObjectName("horizontalFrame1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame1)
        self.horizontalLayout.setContentsMargins(0, 0, 2, 0)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_10 = QtWidgets.QLabel(self.horizontalFrame1)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.span_en = QtWidgets.QToolButton(self.horizontalFrame1)
        self.span_en.setCheckable(True)
        self.span_en.setAutoExclusive(True)
        self.span_en.setObjectName("span_en")
        self.buttonGroup_11 = QtWidgets.QButtonGroup(Dsp_player_mainwindow)
        self.buttonGroup_11.setObjectName("buttonGroup_11")
        self.buttonGroup_11.addButton(self.span_en)
        self.horizontalLayout.addWidget(self.span_en)
        self.span_dis = QtWidgets.QToolButton(self.horizontalFrame1)
        self.span_dis.setCheckable(True)
        self.span_dis.setAutoExclusive(True)
        self.span_dis.setObjectName("span_dis")
        self.buttonGroup_11.addButton(self.span_dis)
        self.horizontalLayout.addWidget(self.span_dis)
        self.gridLayout_6.addWidget(self.horizontalFrame1, 0, 0, 1, 4)
        self.verticalFrame1 = QtWidgets.QFrame(self.pann)
        self.verticalFrame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verticalFrame1.setObjectName("verticalFrame1")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.verticalFrame1)
        self.verticalLayout_12.setContentsMargins(1, 0, 1, 0)
        self.verticalLayout_12.setSpacing(4)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_11 = QtWidgets.QLabel(self.verticalFrame1)
        self.label_11.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        self.pan_sim_dial_2 = QtWidgets.QDial(self.verticalFrame1)
        self.pan_sim_dial_2.setMinimumSize(QtCore.QSize(60, 60))
        self.pan_sim_dial_2.setMaximumSize(QtCore.QSize(75, 75))
        self.pan_sim_dial_2.setProperty("value", 50)
        self.pan_sim_dial_2.setOrientation(QtCore.Qt.Horizontal)
        self.pan_sim_dial_2.setInvertedAppearance(False)
        self.pan_sim_dial_2.setInvertedControls(False)
        self.pan_sim_dial_2.setWrapping(False)
        self.pan_sim_dial_2.setNotchTarget(3.7)
        self.pan_sim_dial_2.setNotchesVisible(True)
        self.pan_sim_dial_2.setObjectName("pan_sim_dial_2")
        self.horizontalLayout_7.addWidget(self.pan_sim_dial_2)
        self.label_12 = QtWidgets.QLabel(self.verticalFrame1)
        self.label_12.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_7.addWidget(self.label_12)
        self.verticalLayout_12.addLayout(self.horizontalLayout_7)
        self.line_27 = QtWidgets.QFrame(self.verticalFrame1)
        self.line_27.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.verticalLayout_12.addWidget(self.line_27)
        self.label_13 = QtWidgets.QLabel(self.verticalFrame1)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_12.addWidget(self.label_13)
        self.line_28 = QtWidgets.QFrame(self.verticalFrame1)
        self.line_28.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.verticalLayout_12.addWidget(self.line_28)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_15 = QtWidgets.QLabel(self.verticalFrame1)
        self.label_15.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_8.addWidget(self.label_15)
        self.pan_spread_dial = QtWidgets.QDial(self.verticalFrame1)
        self.pan_spread_dial.setMinimumSize(QtCore.QSize(60, 60))
        self.pan_spread_dial.setMaximumSize(QtCore.QSize(75, 75))
        self.pan_spread_dial.setOrientation(QtCore.Qt.Horizontal)
        self.pan_spread_dial.setInvertedAppearance(False)
        self.pan_spread_dial.setInvertedControls(False)
        self.pan_spread_dial.setWrapping(False)
        self.pan_spread_dial.setNotchTarget(3.7)
        self.pan_spread_dial.setNotchesVisible(True)
        self.pan_spread_dial.setObjectName("pan_spread_dial")
        self.horizontalLayout_8.addWidget(self.pan_spread_dial)
        self.label_16 = QtWidgets.QLabel(self.verticalFrame1)
        self.label_16.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_8.addWidget(self.label_16)
        self.verticalLayout_12.addLayout(self.horizontalLayout_8)
        self.line_29 = QtWidgets.QFrame(self.verticalFrame1)
        self.line_29.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_29.setObjectName("line_29")
        self.verticalLayout_12.addWidget(self.line_29)
        self.label_14 = QtWidgets.QLabel(self.verticalFrame1)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_12.addWidget(self.label_14)
        self.line_31 = QtWidgets.QFrame(self.verticalFrame1)
        self.line_31.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_31.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_31.setObjectName("line_31")
        self.verticalLayout_12.addWidget(self.line_31)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem5)
        self.gridLayout_6.addWidget(self.verticalFrame1, 1, 0, 1, 1)
        self.gridFrame_3 = QtWidgets.QFrame(self.pann)
        self.gridFrame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.gridFrame_3.setObjectName("gridFrame_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridFrame_3)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setHorizontalSpacing(0)
        self.gridLayout_7.setVerticalSpacing(2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.graphicsView_span_meter = QtWidgets.QGraphicsView(self.gridFrame_3)
        self.graphicsView_span_meter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.graphicsView_span_meter.setObjectName("graphicsView_span_meter")
        self.gridLayout_7.addWidget(self.graphicsView_span_meter, 2, 0, 1, 1)
        self.horizontalFrame_2 = QtWidgets.QFrame(self.gridFrame_3)
        self.horizontalFrame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.horizontalFrame_2.setObjectName("horizontalFrame_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalFrame_2)
        self.horizontalLayout_9.setContentsMargins(0, 2, 2, 0)
        self.horizontalLayout_9.setSpacing(4)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_17 = QtWidgets.QLabel(self.horizontalFrame_2)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_9.addWidget(self.label_17)
        self.meter_en_pan = QtWidgets.QToolButton(self.horizontalFrame_2)
        self.meter_en_pan.setObjectName("meter_en_pan")
        self.horizontalLayout_9.addWidget(self.meter_en_pan)
        self.meter_dis_pan = QtWidgets.QToolButton(self.horizontalFrame_2)
        self.meter_dis_pan.setObjectName("meter_dis_pan")
        self.horizontalLayout_9.addWidget(self.meter_dis_pan)
        self.gridLayout_7.addWidget(self.horizontalFrame_2, 0, 0, 1, 1)
        self.line_30 = QtWidgets.QFrame(self.gridFrame_3)
        self.line_30.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_30.setObjectName("line_30")
        self.gridLayout_7.addWidget(self.line_30, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.gridFrame_3, 1, 2, 1, 2)
        self.gridLayout_4.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.graphicsView_binaurp_3 = QtWidgets.QGraphicsView(self.pann)
        self.graphicsView_binaurp_3.setObjectName("graphicsView_binaurp_3")
        self.gridLayout_10.addWidget(self.graphicsView_binaurp_3, 1, 1, 1, 1)
        self.horizontalFrame_5 = QtWidgets.QFrame(self.pann)
        self.horizontalFrame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.horizontalFrame_5.setObjectName("horizontalFrame_5")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.horizontalFrame_5)
        self.horizontalLayout_17.setContentsMargins(0, 0, 2, 0)
        self.horizontalLayout_17.setSpacing(4)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_32 = QtWidgets.QLabel(self.horizontalFrame_5)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_17.addWidget(self.label_32)
        self.binaurp_en_3 = QtWidgets.QToolButton(self.horizontalFrame_5)
        self.binaurp_en_3.setCheckable(True)
        self.binaurp_en_3.setAutoExclusive(True)
        self.binaurp_en_3.setObjectName("binaurp_en_3")
        self.buttonGroup_12 = QtWidgets.QButtonGroup(Dsp_player_mainwindow)
        self.buttonGroup_12.setObjectName("buttonGroup_12")
        self.buttonGroup_12.addButton(self.binaurp_en_3)
        self.horizontalLayout_17.addWidget(self.binaurp_en_3)
        self.binaurp_dis_3 = QtWidgets.QToolButton(self.horizontalFrame_5)
        self.binaurp_dis_3.setCheckable(True)
        self.binaurp_dis_3.setAutoExclusive(True)
        self.binaurp_dis_3.setObjectName("binaurp_dis_3")
        self.buttonGroup_12.addButton(self.binaurp_dis_3)
        self.horizontalLayout_17.addWidget(self.binaurp_dis_3)
        self.gridLayout_10.addWidget(self.horizontalFrame_5, 0, 0, 1, 4)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.verticalFrame_11 = QtWidgets.QFrame(self.pann)
        self.verticalFrame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verticalFrame_11.setObjectName("verticalFrame_11")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.verticalFrame_11)
        self.verticalLayout_15.setContentsMargins(1, 0, 1, 0)
        self.verticalLayout_15.setSpacing(4)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_34 = QtWidgets.QLabel(self.verticalFrame_11)
        self.label_34.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_20.addWidget(self.label_34)
        self.azimuth_dial_5 = QtWidgets.QDial(self.verticalFrame_11)
        self.azimuth_dial_5.setMinimumSize(QtCore.QSize(60, 60))
        self.azimuth_dial_5.setMaximumSize(QtCore.QSize(75, 75))
        self.azimuth_dial_5.setProperty("value", 50)
        self.azimuth_dial_5.setOrientation(QtCore.Qt.Horizontal)
        self.azimuth_dial_5.setInvertedAppearance(False)
        self.azimuth_dial_5.setInvertedControls(False)
        self.azimuth_dial_5.setWrapping(False)
        self.azimuth_dial_5.setNotchTarget(3.7)
        self.azimuth_dial_5.setNotchesVisible(True)
        self.azimuth_dial_5.setObjectName("azimuth_dial_5")
        self.horizontalLayout_20.addWidget(self.azimuth_dial_5)
        self.label_35 = QtWidgets.QLabel(self.verticalFrame_11)
        self.label_35.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_20.addWidget(self.label_35)
        self.verticalLayout_15.addLayout(self.horizontalLayout_20)
        self.line_42 = QtWidgets.QFrame(self.verticalFrame_11)
        self.line_42.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_42.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_42.setObjectName("line_42")
        self.verticalLayout_15.addWidget(self.line_42)
        self.label_36 = QtWidgets.QLabel(self.verticalFrame_11)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_15.addWidget(self.label_36)
        self.line_43 = QtWidgets.QFrame(self.verticalFrame_11)
        self.line_43.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_43.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_43.setObjectName("line_43")
        self.verticalLayout_15.addWidget(self.line_43)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_37 = QtWidgets.QLabel(self.verticalFrame_11)
        self.label_37.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_21.addWidget(self.label_37)
        self.azimuth_span_2 = QtWidgets.QDial(self.verticalFrame_11)
        self.azimuth_span_2.setMinimumSize(QtCore.QSize(60, 60))
        self.azimuth_span_2.setMaximumSize(QtCore.QSize(75, 75))
        self.azimuth_span_2.setOrientation(QtCore.Qt.Horizontal)
        self.azimuth_span_2.setInvertedAppearance(False)
        self.azimuth_span_2.setInvertedControls(False)
        self.azimuth_span_2.setWrapping(False)
        self.azimuth_span_2.setNotchTarget(3.7)
        self.azimuth_span_2.setNotchesVisible(True)
        self.azimuth_span_2.setObjectName("azimuth_span_2")
        self.horizontalLayout_21.addWidget(self.azimuth_span_2)
        self.label_38 = QtWidgets.QLabel(self.verticalFrame_11)
        self.label_38.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_21.addWidget(self.label_38)
        self.verticalLayout_15.addLayout(self.horizontalLayout_21)
        self.line_44 = QtWidgets.QFrame(self.verticalFrame_11)
        self.line_44.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_44.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_44.setObjectName("line_44")
        self.verticalLayout_15.addWidget(self.line_44)
        self.label_39 = QtWidgets.QLabel(self.verticalFrame_11)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_15.addWidget(self.label_39)
        self.line_45 = QtWidgets.QFrame(self.verticalFrame_11)
        self.line_45.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_45.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_45.setObjectName("line_45")
        self.verticalLayout_15.addWidget(self.line_45)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem6)
        self.horizontalLayout_19.addWidget(self.verticalFrame_11)
        self.verticalFrame_12 = QtWidgets.QFrame(self.pann)
        self.verticalFrame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verticalFrame_12.setObjectName("verticalFrame_12")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.verticalFrame_12)
        self.verticalLayout_16.setContentsMargins(1, 0, 1, 0)
        self.verticalLayout_16.setSpacing(4)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setSpacing(0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_40 = QtWidgets.QLabel(self.verticalFrame_12)
        self.label_40.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_22.addWidget(self.label_40)
        self.elev_dial3_2 = QtWidgets.QDial(self.verticalFrame_12)
        self.elev_dial3_2.setMinimumSize(QtCore.QSize(60, 60))
        self.elev_dial3_2.setMaximumSize(QtCore.QSize(75, 75))
        self.elev_dial3_2.setProperty("value", 50)
        self.elev_dial3_2.setOrientation(QtCore.Qt.Horizontal)
        self.elev_dial3_2.setInvertedAppearance(False)
        self.elev_dial3_2.setInvertedControls(False)
        self.elev_dial3_2.setWrapping(False)
        self.elev_dial3_2.setNotchTarget(3.7)
        self.elev_dial3_2.setNotchesVisible(True)
        self.elev_dial3_2.setObjectName("elev_dial3_2")
        self.horizontalLayout_22.addWidget(self.elev_dial3_2)
        self.label_41 = QtWidgets.QLabel(self.verticalFrame_12)
        self.label_41.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_22.addWidget(self.label_41)
        self.verticalLayout_16.addLayout(self.horizontalLayout_22)
        self.line_46 = QtWidgets.QFrame(self.verticalFrame_12)
        self.line_46.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_46.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_46.setObjectName("line_46")
        self.verticalLayout_16.addWidget(self.line_46)
        self.label_42 = QtWidgets.QLabel(self.verticalFrame_12)
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_16.addWidget(self.label_42)
        self.line_47 = QtWidgets.QFrame(self.verticalFrame_12)
        self.line_47.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_47.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_47.setObjectName("line_47")
        self.verticalLayout_16.addWidget(self.line_47)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_43 = QtWidgets.QLabel(self.verticalFrame_12)
        self.label_43.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_23.addWidget(self.label_43)
        self.elev_span_d_2 = QtWidgets.QDial(self.verticalFrame_12)
        self.elev_span_d_2.setMinimumSize(QtCore.QSize(60, 60))
        self.elev_span_d_2.setMaximumSize(QtCore.QSize(75, 75))
        self.elev_span_d_2.setOrientation(QtCore.Qt.Horizontal)
        self.elev_span_d_2.setInvertedAppearance(False)
        self.elev_span_d_2.setInvertedControls(False)
        self.elev_span_d_2.setWrapping(False)
        self.elev_span_d_2.setNotchTarget(3.7)
        self.elev_span_d_2.setNotchesVisible(True)
        self.elev_span_d_2.setObjectName("elev_span_d_2")
        self.horizontalLayout_23.addWidget(self.elev_span_d_2)
        self.label_44 = QtWidgets.QLabel(self.verticalFrame_12)
        self.label_44.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_23.addWidget(self.label_44)
        self.verticalLayout_16.addLayout(self.horizontalLayout_23)
        self.line_48 = QtWidgets.QFrame(self.verticalFrame_12)
        self.line_48.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_48.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_48.setObjectName("line_48")
        self.verticalLayout_16.addWidget(self.line_48)
        self.label_45 = QtWidgets.QLabel(self.verticalFrame_12)
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_16.addWidget(self.label_45)
        self.line_49 = QtWidgets.QFrame(self.verticalFrame_12)
        self.line_49.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_49.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_49.setObjectName("line_49")
        self.verticalLayout_16.addWidget(self.line_49)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem7)
        self.horizontalLayout_19.addWidget(self.verticalFrame_12)
        self.gridLayout_10.addLayout(self.horizontalLayout_19, 1, 0, 1, 1)
        self.gridFrame_5 = QtWidgets.QFrame(self.pann)
        self.gridFrame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.gridFrame_5.setObjectName("gridFrame_5")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.gridFrame_5)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setHorizontalSpacing(0)
        self.gridLayout_11.setVerticalSpacing(2)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.graphicsView_binaurp_meter_3 = QtWidgets.QGraphicsView(self.gridFrame_5)
        self.graphicsView_binaurp_meter_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.graphicsView_binaurp_meter_3.setObjectName("graphicsView_binaurp_meter_3")
        self.gridLayout_11.addWidget(self.graphicsView_binaurp_meter_3, 2, 0, 1, 1)
        self.horizontalFrame_6 = QtWidgets.QFrame(self.gridFrame_5)
        self.horizontalFrame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.horizontalFrame_6.setObjectName("horizontalFrame_6")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.horizontalFrame_6)
        self.horizontalLayout_18.setContentsMargins(0, 2, 2, 0)
        self.horizontalLayout_18.setSpacing(4)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_33 = QtWidgets.QLabel(self.horizontalFrame_6)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_18.addWidget(self.label_33)
        self.meter_en_binaurp_3 = QtWidgets.QToolButton(self.horizontalFrame_6)
        self.meter_en_binaurp_3.setCheckable(True)
        self.meter_en_binaurp_3.setAutoExclusive(True)
        self.meter_en_binaurp_3.setObjectName("meter_en_binaurp_3")
        self.buttonGroup_13 = QtWidgets.QButtonGroup(Dsp_player_mainwindow)
        self.buttonGroup_13.setObjectName("buttonGroup_13")
        self.buttonGroup_13.addButton(self.meter_en_binaurp_3)
        self.horizontalLayout_18.addWidget(self.meter_en_binaurp_3)
        self.meter_dis_binaurp_3 = QtWidgets.QToolButton(self.horizontalFrame_6)
        self.meter_dis_binaurp_3.setCheckable(True)
        self.meter_dis_binaurp_3.setAutoExclusive(True)
        self.meter_dis_binaurp_3.setObjectName("meter_dis_binaurp_3")
        self.buttonGroup_13.addButton(self.meter_dis_binaurp_3)
        self.horizontalLayout_18.addWidget(self.meter_dis_binaurp_3)
        self.gridLayout_11.addWidget(self.horizontalFrame_6, 0, 0, 1, 1)
        self.line_41 = QtWidgets.QFrame(self.gridFrame_5)
        self.line_41.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_41.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_41.setObjectName("line_41")
        self.gridLayout_11.addWidget(self.line_41, 1, 0, 1, 1)
        self.gridLayout_10.addWidget(self.gridFrame_5, 1, 2, 1, 2)
        self.gridLayout_4.addLayout(self.gridLayout_10, 1, 0, 1, 1)
        self.tabWidget.addTab(self.pann, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.outer_frame_grid, 0, 0, 1, 1)
        self.frame2 = QtWidgets.QFrame(self.centralwidget)
        self.frame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame2.setObjectName("frame2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame2)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.amp_dial = QtWidgets.QDial(self.frame2)
        self.amp_dial.setMinimumSize(QtCore.QSize(60, 60))
        self.amp_dial.setMaximumSize(QtCore.QSize(90, 75))
        self.amp_dial.setMinimum(0)
        self.amp_dial.setMaximum(300)
        self.amp_dial.setSingleStep(1)
        self.amp_dial.setOrientation(QtCore.Qt.Horizontal)
        self.amp_dial.setInvertedAppearance(False)
        self.amp_dial.setInvertedControls(False)
        self.amp_dial.setWrapping(False)
        self.amp_dial.setNotchTarget(30.0)
        self.amp_dial.setNotchesVisible(True)
        self.amp_dial.setObjectName("amp_dial")
        self.verticalLayout_9.addWidget(self.amp_dial)
        self.line_26 = QtWidgets.QFrame(self.frame2)
        self.line_26.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.verticalLayout_9.addWidget(self.line_26)
        self.label_2 = QtWidgets.QLabel(self.frame2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_9.addWidget(self.label_2)
        self.line_25 = QtWidgets.QFrame(self.frame2)
        self.line_25.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.verticalLayout_9.addWidget(self.line_25)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(2, 0, 2, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.master_vu_meter_graph = PlotWidget(self.frame2)
        self.master_vu_meter_graph.setEnabled(False)
        self.master_vu_meter_graph.setMaximumSize(QtCore.QSize(100, 16777215))
        self.master_vu_meter_graph.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.master_vu_meter_graph.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.master_vu_meter_graph.setInteractive(False)
        self.master_vu_meter_graph.setObjectName("master_vu_meter_graph")
        self.horizontalLayout_10.addWidget(self.master_vu_meter_graph)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.line_32 = QtWidgets.QFrame(self.frame2)
        self.line_32.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_32.setObjectName("line_32")
        self.verticalLayout_9.addWidget(self.line_32)
        self.label_18 = QtWidgets.QLabel(self.frame2)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_9.addWidget(self.label_18)
        self.line_33 = QtWidgets.QFrame(self.frame2)
        self.line_33.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_33.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_33.setObjectName("line_33")
        self.verticalLayout_9.addWidget(self.line_33)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem8)
        self.server_on_toolB = QtWidgets.QToolButton(self.frame2)
        self.server_on_toolB.setMinimumSize(QtCore.QSize(80, 0))
        self.server_on_toolB.setMaximumSize(QtCore.QSize(900, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.server_on_toolB.setFont(font)
        self.server_on_toolB.setCheckable(True)
        self.server_on_toolB.setAutoExclusive(True)
        self.server_on_toolB.setObjectName("server_on_toolB")
        self.buttonGroup_10 = QtWidgets.QButtonGroup(Dsp_player_mainwindow)
        self.buttonGroup_10.setObjectName("buttonGroup_10")
        self.buttonGroup_10.addButton(self.server_on_toolB)
        self.verticalLayout_9.addWidget(self.server_on_toolB)
        self.server_off_toolB = QtWidgets.QToolButton(self.frame2)
        self.server_off_toolB.setMinimumSize(QtCore.QSize(80, 0))
        self.server_off_toolB.setMaximumSize(QtCore.QSize(900, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.server_off_toolB.setFont(font)
        self.server_off_toolB.setCheckable(True)
        self.server_off_toolB.setAutoExclusive(True)
        self.server_off_toolB.setObjectName("server_off_toolB")
        self.buttonGroup_10.addButton(self.server_off_toolB)
        self.verticalLayout_9.addWidget(self.server_off_toolB)
        self.gridLayout_2.addWidget(self.frame2, 0, 1, 1, 1)
        Dsp_player_mainwindow.setCentralWidget(self.centralwidget)
        self.actionSettings = QtWidgets.QAction(Dsp_player_mainwindow)
        self.actionSettings.setObjectName("actionSettings")

        self.retranslateUi(Dsp_player_mainwindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dsp_player_mainwindow)

    def retranslateUi(self, Dsp_player_mainwindow):
        _translate = QtCore.QCoreApplication.translate
        Dsp_player_mainwindow.setWindowTitle(_translate("Dsp_player_mainwindow", "DSP PLayer"))
        self.comboBox.setItemText(0, _translate("Dsp_player_mainwindow", "Flat"))
        self.comboBox.setItemText(1, _translate("Dsp_player_mainwindow", "Bass"))
        self.EnableB.setText(_translate("Dsp_player_mainwindow", "Enable"))
        self.DisableB.setText(_translate("Dsp_player_mainwindow", "Disable"))
        self.label_9.setText(_translate("Dsp_player_mainwindow", "High shelf"))
        self.hp_2.setText(_translate("Dsp_player_mainwindow", "2"))
        self.hp_3.setText(_translate("Dsp_player_mainwindow", "2"))
        self.hp_4.setText(_translate("Dsp_player_mainwindow", "2"))
        self.hp_5.setText(_translate("Dsp_player_mainwindow", "2"))
        self.hp_6.setText(_translate("Dsp_player_mainwindow", "2"))
        self.hp_7.setText(_translate("Dsp_player_mainwindow", "2"))
        self.hp_8.setText(_translate("Dsp_player_mainwindow", "2"))
        self.label_8.setText(_translate("Dsp_player_mainwindow", "Low shelf"))
        self.lp_2.setText(_translate("Dsp_player_mainwindow", "1"))
        self.lp_3.setText(_translate("Dsp_player_mainwindow", "1"))
        self.lp_5.setText(_translate("Dsp_player_mainwindow", "1"))
        self.lp_4.setText(_translate("Dsp_player_mainwindow", "1"))
        self.lp_6.setText(_translate("Dsp_player_mainwindow", "1"))
        self.lp_7.setText(_translate("Dsp_player_mainwindow", "1"))
        self.lp_8.setText(_translate("Dsp_player_mainwindow", "1"))
        self.label_7.setText(_translate("Dsp_player_mainwindow", "Peak/Notch"))
        self.pn_2.setText(_translate("Dsp_player_mainwindow", "0"))
        self.pn_3.setText(_translate("Dsp_player_mainwindow", "0"))
        self.pn_4.setText(_translate("Dsp_player_mainwindow", "0"))
        self.pn_5.setText(_translate("Dsp_player_mainwindow", "0"))
        self.pn_6.setText(_translate("Dsp_player_mainwindow", "0"))
        self.pn_7.setText(_translate("Dsp_player_mainwindow", "0"))
        self.pn_8.setText(_translate("Dsp_player_mainwindow", "0"))
        self.label_3.setText(_translate("Dsp_player_mainwindow", "Amp"))
        self.label_4.setText(_translate("Dsp_player_mainwindow", "Freq"))
        self.label_5.setText(_translate("Dsp_player_mainwindow", "Spred"))
        self.label_6.setText(_translate("Dsp_player_mainwindow", "Band"))
        self.bnd1.setText(_translate("Dsp_player_mainwindow", "1"))
        self.bnd2.setText(_translate("Dsp_player_mainwindow", "2"))
        self.bnd3.setText(_translate("Dsp_player_mainwindow", "3"))
        self.bnd4.setText(_translate("Dsp_player_mainwindow", "4"))
        self.bnd5.setText(_translate("Dsp_player_mainwindow", "5"))
        self.bnd6.setText(_translate("Dsp_player_mainwindow", "6"))
        self.bnd7.setText(_translate("Dsp_player_mainwindow", "7"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.para_eq), _translate("Dsp_player_mainwindow", "Parametric EQ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dsp_player_mainwindow", "Audio FX"))
        self.label_10.setText(_translate("Dsp_player_mainwindow", "Panning"))
        self.span_en.setText(_translate("Dsp_player_mainwindow", "Enable"))
        self.span_dis.setText(_translate("Dsp_player_mainwindow", "Disable"))
        self.label_11.setText(_translate("Dsp_player_mainwindow", "L"))
        self.label_12.setText(_translate("Dsp_player_mainwindow", "R"))
        self.label_13.setText(_translate("Dsp_player_mainwindow", "Panning"))
        self.label_15.setText(_translate("Dsp_player_mainwindow", "0"))
        self.label_16.setText(_translate("Dsp_player_mainwindow", "1"))
        self.label_14.setText(_translate("Dsp_player_mainwindow", "Spread"))
        self.label_17.setText(_translate("Dsp_player_mainwindow", "Meter"))
        self.meter_en_pan.setText(_translate("Dsp_player_mainwindow", "Enable"))
        self.meter_dis_pan.setText(_translate("Dsp_player_mainwindow", "Disable"))
        self.label_32.setText(_translate("Dsp_player_mainwindow", "BinAural Panning"))
        self.binaurp_en_3.setText(_translate("Dsp_player_mainwindow", "Enable"))
        self.binaurp_dis_3.setText(_translate("Dsp_player_mainwindow", "Disable"))
        self.label_34.setText(_translate("Dsp_player_mainwindow", "0"))
        self.label_35.setText(_translate("Dsp_player_mainwindow", "1"))
        self.label_36.setText(_translate("Dsp_player_mainwindow", "Azimuth"))
        self.label_37.setText(_translate("Dsp_player_mainwindow", "0"))
        self.label_38.setText(_translate("Dsp_player_mainwindow", "1"))
        self.label_39.setText(_translate("Dsp_player_mainwindow", "Azispan"))
        self.label_40.setText(_translate("Dsp_player_mainwindow", "0"))
        self.label_41.setText(_translate("Dsp_player_mainwindow", "1"))
        self.label_42.setText(_translate("Dsp_player_mainwindow", "Elevation"))
        self.label_43.setText(_translate("Dsp_player_mainwindow", "0"))
        self.label_44.setText(_translate("Dsp_player_mainwindow", "1"))
        self.label_45.setText(_translate("Dsp_player_mainwindow", "Elespan"))
        self.label_33.setText(_translate("Dsp_player_mainwindow", "Meter"))
        self.meter_en_binaurp_3.setText(_translate("Dsp_player_mainwindow", "Enable"))
        self.meter_dis_binaurp_3.setText(_translate("Dsp_player_mainwindow", "Disable"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pann), _translate("Dsp_player_mainwindow", "Panning"))
        self.label_2.setText(_translate("Dsp_player_mainwindow", "Master"))
        self.label_18.setText(_translate("Dsp_player_mainwindow", "Master Amp"))
        self.server_on_toolB.setText(_translate("Dsp_player_mainwindow", "Server On"))
        self.server_off_toolB.setText(_translate("Dsp_player_mainwindow", "Server Off"))
        self.actionSettings.setText(_translate("Dsp_player_mainwindow", "Settings"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dsp_player_mainwindow = QtWidgets.QMainWindow()
    ui = Ui_Dsp_player_mainwindow()
    ui.setupUi(Dsp_player_mainwindow)
    Dsp_player_mainwindow.show()
    sys.exit(app.exec_())
